### PR TITLE
[btcrelay] init version of btcrelay

### PR DESCRIPTION
**Pull request by LeoHChen**
* prototype of btcrelay
* build support
* add LICENSE file

Signed-off-by: Leo Chen <leo@harmony.one>

### CODE REVIEW

**Comment by Daniel-VDM** [comment]
I don’t see why this needs to be in the main repo. 

IMHO should be in it’s own repo or in the harmony-one/onebtc repo. 

According to the interlay spec, a staked relayer is suppose to run their own btc node and report/verify block headers to/from the relayer contract and possibly also interact with the relayer’s governance mechanism. If this is what this code is for (with is unclear by the PR message btw) then it def needs to be somewhere else. 

If the code is just for some tool to fetch btc block info then this should also not be in the main repo and prob be made as a script.

**Review by Daniel-VDM — CHANGES_REQUESTED** [review]
Ref comment above

**Comment by gupadhyaya** [comment]
@LeoHChen why this needs to be here? let's have all modules and tools under: https://github.com/harmony-one/onebtc

**Comment by LeoHChen** [comment]
okay, I'll move it to onebtc repo. The staked relayer will run the btc node, and the relay tool is a client of the btc node, it needs to fetch block info from btc node, and feed the data to the relayer contract.

**Pull request closed without merging**
