### PR TITLE
[blockchain] singleflight on tagged rlp registry

### PR DESCRIPTION
**Pull request by fxfactorial**
current work in another PR has many situation of parallelism , so during race condition testing, I hit this open issue. 

> by doing a blk.ShardID() in one thread and a rlp.DecodeBytes in another thread, they both hit up 
> the global tagged RLP registry and it exploded

### CODE REVIEW

**Comment by JackyWYX** [comment]
Interesting. The problems seems to be the race condition rooted in higher function calls. Just curious is it challenging to locate where the race happens in function calls?

**Comment by fxfactorial** [comment]
The root isn’t higher function calls , need to allow only 1 thread at a time to use the registry

**Comment by JackyWYX** [comment]
> The root isn’t higher function calls , need to allow only 1 thread at a time to use the registry

Gotta. Thanks for you explanation :)

**Comment by rlan35** [comment]
Is this tested with the same race condition setting and it's gone?

**Comment by fxfactorial** [comment]
It fixed on my branch work but it’s not too hard to setup a self contained example

**Pull request merged**
