### PR TITLE
update core code to use swapped BLS sig

### PR DESCRIPTION
**Pull request by rlan35**

### CODE REVIEW

**Comment by rlan35** [comment]
Jenkins, test this please!

**Comment by rlan35** [comment]
Jenkins, test this please!

**Comment by rlan35** [comment]
Jenkins, test this please!

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by rlan35** [comment]
Jenkins, test this please.

**Comment by rlan35** [comment]
Jenkins, test this please.

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Pull request merged**
