### PR TITLE
update node.sh to avoid adding config multiple times

### PR DESCRIPTION
**Pull request by lvyelin**
Also fix a message to use "pkill" instead of "kill" to terminate harmony

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Pull request merged**
