### PR TITLE
Increase suggested gas and reduce block gas limit

### PR DESCRIPTION
**Pull request by rlan35**
Increase suggested gas to be 70 percentile and max suggested gas to 1000 gwei.

Reduce block gas limit to be 30M.

### CODE REVIEW

**Review by MaxMustermann2 — APPROVED** [review]

**Comment by MaxMustermann2** [comment]
The build is complaining about a race error, but it's in a bunch of parallel tests. I don't think they need to be parallel in the first place; that can be fixed by the following patch.
```diff
diff --git a/p2p/tests/host_test.go b/p2p/tests/host_test.go
index 40cb9d5d..b994a04b 100644
--- a/p2p/tests/host_test.go
+++ b/p2p/tests/host_test.go
@@ -8,7 +8,6 @@ import (
 )
 
 func TestHostSetup(t *testing.T) {
-	t.Parallel()
 
 	hostData := helpers.Hosts[0]
 	host, pubKey, err := helpers.GenerateHost(hostData.IP, hostData.Port)
@@ -25,7 +24,6 @@ func TestHostSetup(t *testing.T) {
 }
 
 func TestAddPeer(t *testing.T) {
-	t.Parallel()
 
 	hostData := helpers.Hosts[0]
 	host, _, err := helpers.GenerateHost(hostData.IP, hostData.Port)
@@ -64,7 +62,6 @@ func TestAddPeer(t *testing.T) {
 }*/
 
 func TestConnectionToInvalidPeer(t *testing.T) {
-	t.Parallel()
 
 	hostData := helpers.Hosts[0]
 	host, _, err := helpers.GenerateHost(hostData.IP, hostData.Port)
```

**Comment by GheisMohammadiBC** [comment]
Looks good 👍

**Review by GheisMohammadi — APPROVED** [review]
looks good

**Comment by MaxMustermann2** [comment]
Superseded by #4222

**Pull request closed without merging**
