### PR TITLE
Remove special eth txn in block and block proposal logic.

### PR DESCRIPTION
**Pull request by rlan35**
Revert some of the recently committed code to add eth transaction in block structure, which is a bit cumbersome for both code logic and data structure.

Actually we can do the following to merge ethereum transaction in existing harmony txn in the block:

For eth transaction, we convert it to harmony txn with ShardID and ToShardID equal to the shard ID it's meant to. This way, eth txns can be stored the same way as harmony txn in the block.

TODOs: 

1. implement special logic in the transaction hash() function to make sure for eth txns, the ShardID and ToShardID are not included in the hash since they are not used in the original ethereum txn signing.
2. implement logic to separate ethereum transaction out from harmony txns based on the ChainID.

### CODE REVIEW

**Review by Daniel-VDM — APPROVED** [review]
Looks good to me, would check to make sure it passes all build tests tho.

As of commit b43b8e1b2334812ea7dfaeaf77d4a83fa8d43a76 it passed on my machine, not sure why it would not pass on Travis, maybe race?

**Comment by rlan35** [comment]
Jenkins, test this please.

**Comment by SebastianJ** [comment]
LGTM - building & testing locally works fine, Travis is still struggling tho:

```
--- FAIL: TestCommitTransactions (0.00s)
2609panic: runtime error: index out of range [0] with length 0 [recovered]
2610	panic: runtime error: index out of range [0] with length 0
2611
2612goroutine 8 [running]:
2613testing.tRunner.func1.1(0xf45ba0, 0xc00042ed20)
2614	/home/travis/.gimme/versions/go1.14.linux.amd64/src/testing/testing.go:941 +0x3d0
2615testing.tRunner.func1(0xc0000c86c0)
2616	/home/travis/.gimme/versions/go1.14.linux.amd64/src/testing/testing.go:944 +0x3f9
2617panic(0xf45ba0, 0xc00042ed20)
2618	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/panic.go:967 +0x15d
2619github.com/harmony-one/harmony/core/types.NewTransactionsByPriceAndNonce(0x12f77c0, 0xc000053a70, 0xc000435260, 0x1306bc0)
2620	/home/travis/gopath/src/github.com/harmony-one/harmony/core/types/transaction.go:560 +0x513
2621github.com/harmony-one/harmony/node/worker.(*Worker).CommitTransactions(0xc0000aab90, 0xc000435260, 0x0, 0x0, 0x0, 0xba2e84dd2f63c94a, 0xb06e12a62ff5846, 0x3bc19f3f, 0x0, 0xc0000a46e0)
2622	/home/travis/gopath/src/github.com/harmony-one/harmony/node/worker/worker.go:137 +0x6f
2623github.com/harmony-one/harmony/node/worker.TestCommitTransactions(0xc0000c86c0)
2624	/home/travis/gopath/src/github.com/harmony-one/harmony/node/worker/worker_test.go:84 +0x583
2625testing.tRunner(0xc0000c86c0, 0x1189f70)
2626	/home/travis/.gimme/versions/go1.14.linux.amd64/src/testing/testing.go:992 +0xdc
2627created by testing.(*T).Run
2628	/home/travis/.gimme/versions/go1.14.linux.amd64/src/testing/testing.go:1043 +0x357
2629FAIL	github.com/harmony-one/harmony/node/worker	0.067s
```

**Review by SebastianJ — APPROVED** [review]

**Comment by rlan35** [comment]
> LGTM - building & testing locally works fine, Travis is still struggling tho:
> 
> ```
> --- FAIL: TestCommitTransactions (0.00s)
> 2609panic: runtime error: index out of range [0] with length 0 [recovered]
> 2610	panic: runtime error: index out of range [0] with length 0
> 2611
> 2612goroutine 8 [running]:
> 2613testing.tRunner.func1.1(0xf45ba0, 0xc00042ed20)
> 2614	/home/travis/.gimme/versions/go1.14.linux.amd64/src/testing/testing.go:941 +0x3d0
> 2615testing.tRunner.func1(0xc0000c86c0)
> 2616	/home/travis/.gimme/versions/go1.14.linux.amd64/src/testing/testing.go:944 +0x3f9
> 2617panic(0xf45ba0, 0xc00042ed20)
> 2618	/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/panic.go:967 +0x15d
> 2619github.com/harmony-one/harmony/core/types.NewTransactionsByPriceAndNonce(0x12f77c0, 0xc000053a70, 0xc000435260, 0x1306bc0)
> 2620	/home/travis/gopath/src/github.com/harmony-one/harmony/core/types/transaction.go:560 +0x513
> 2621github.com/harmony-one/harmony/node/worker.(*Worker).CommitTransactions(0xc0000aab90, 0xc000435260, 0x0, 0x0, 0x0, 0xba2e84dd2f63c94a, 0xb06e12a62ff5846, 0x3bc19f3f, 0x0, 0xc0000a46e0)
> 2622	/home/travis/gopath/src/github.com/harmony-one/harmony/node/worker/worker.go:137 +0x6f
> 2623github.com/harmony-one/harmony/node/worker.TestCommitTransactions(0xc0000c86c0)
> 2624	/home/travis/gopath/src/github.com/harmony-one/harmony/node/worker/worker_test.go:84 +0x583
> 2625testing.tRunner(0xc0000c86c0, 0x1189f70)
> 2626	/home/travis/.gimme/versions/go1.14.linux.amd64/src/testing/testing.go:992 +0xdc
> 2627created by testing.(*T).Run
> 2628	/home/travis/.gimme/versions/go1.14.linux.amd64/src/testing/testing.go:1043 +0x357
> 2629FAIL	github.com/harmony-one/harmony/node/worker	0.067s
> ```

update with the latest main branch solved the problem

**Pull request merged**
