### PR TITLE
[tracer] Fix bug of go version trace_block

### PR DESCRIPTION
**Pull request by peekpi**
In some complicated cases, the go version 'trace_block' results in an incorrect result. This was reported by @LuttyYang  and @jhd2best when they tested Rosetta.
For example, for [0x87f1222a242bc5c187557e4659e095533c9fd6c7ad810c360a88168e6c5250fc][tx], the trace results of the GO version(#3686) are not the same as the trace results of the JS version(#3640). And the result of JS version is correct.
1. curl to get GO version trace result
```
curl --location --request POST 'http://internal-ext-65-node-ip:9501' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "trace_transaction",
    "params": [
        "0x87f1222a242bc5c187557e4659e095533c9fd6c7ad810c360a88168e6c5250fc"
    ]
}'
```
2. curl to get JS version trace result
```
curl -H "Content-Type: application/json" -d '{"id": 1, "method": "debug_traceTransaction", "params": ["0x87f1222a242bc5c187557e4659e095533c9fd6c7ad810c360a88168e6c5250fc", {"Tracer":"blockTracer"}]}' http://internal-ext-65-node-ip:9501
```

[tx]: https://explorer.harmony.one/tx/0x87f1222a242bc5c187557e4659e095533c9fd6c7ad810c360a88168e6c5250fc

### CODE REVIEW

**Review by LuttyYang — APPROVED** [review]
LGTM

**Comment by sophoah** [comment]
@peekpi is it possible to have this feature enabled on demand (through harmony config and cli args) ? We know this only allow be used by explorer archival node, but considering the additional disk space it takes, having an option to to enable it or not would be useful.

**Comment by sophoah** [comment]
@peekpi I just tested this PR and the trace go and trace js are still different with 0x87f1222a242bc5c187557e4659e095533c9fd6c7ad810c360a88168e6c5250fc

**Comment by peekpi** [comment]
> @peekpi I just tested this PR and the trace go and trace js are still different with 0x87f1222a242bc5c187557e4659e095533c9fd6c7ad810c360a88168e6c5250fc

Yeah, it's not exactly the same. go-trace extends js-trace, adding revert error messages. You can save trace results to files and compare them with the json-diff tool.
install: `npm install -g json-diff`

**Comment by sophoah** [comment]
hey @peekpi I tested again after your last commit. trace go version is failing:
curl -s --location --request POST 'http://localhost:9501' --header 'Content-Type: application/json' --data-raw '{                                                                                                             "id": "1",
    "jsonrpc": "2.0",
    "method": "trace_transaction",
    "params": [
        "0x39d186b8a376a6793a4d663505005217de7bad06994ceef5d3131566187693b6"
    ]
}' 
{"jsonrpc":"2.0","id":"1","error":{"code":-32000,"message":"json: error calling MarshalJSON for type json.RawMessage: invalid character '0' after object key:value pair"}}

**Comment by sophoah** [comment]
@peekpi as discussed over dm, thanks to look at why the go/js output for a normal tx is different

**Comment by sophoah** [comment]
tests are now ok with go/js for normal tx (expected to have the same output), and different as expected for block with reverted tx. go version will have additional data regarding the reverted tx

**Pull request merged**
