### PR TITLE
[Pangaea] 1000 total nodes w/ 80 internal

### PR DESCRIPTION
**Pull request by xChickens**

### CODE REVIEW

**Comment by LeoHChen** [comment]
are the foundational nodes all new keys, or just replace the 293?  And have you uploaded the keys to the s3 bucket?

**Comment by alajko** [comment]
@xChickens We might want to merge my PR first which has the 278 replacement keys.

**Comment by xChickens** [comment]
> have you uploaded all keys to s3? And you need to change the pangaea_keys.txt in experiment-deploy/configs directory.

Working on it

**Comment by xChickens** [comment]
https://github.com/harmony-one/experiment-deploy/pull/85
pangaea_keys.txt change

Keys are uploaded to s3.

**Pull request merged**
