### PR TITLE
transaction throttling with network-level configuration

### PR DESCRIPTION
**Pull request by denniswon**
## Issue

https://github.com/harmony-one/harmony/issues/1267

#### Test Coverage Data

* Before
* After

dennis.won@mp-dennisw-ml2:~/go/src/github.com/harmony-one/harmony/internal/configs/sharding (txs_throttle) $ go test --cover
PASS
coverage: 17.1% of statements
ok  	github.com/harmony-one/harmony/internal/configs/sharding	0.080s

dennis.won@mp-dennisw-ml2:~/go/src/github.com/harmony-one/harmony/node (txs_throttle) $ go test --cover
wait 5 seconds to terminate the process ...
ok  	github.com/harmony-one/harmony/node	10.933s

#### Test/Run Logs

Localnet testing:
{"level":"debug","port":"9000","ip":"127.0.0.1","MaxTxAmountLimit":1000,"Tx amount":12727183826875318272,"caller":"/Users/dennis.won/go/src/github.com/harmony-one/harmony/node/worker/worker.go:79","time":"2019-08-07T13:28:33-07:00","message":"Throttling tx with max amount limit"}
{"level":"info","port":"9000","ip":"127.0.0.1","txThrottleFlag":"Invalid","caller":"/Users/dennis.won/go/src/github.com/harmony-one/harmony/node/worker/worker.go:119","time":"2019-08-07T13:28:33-07:00","message":"Transaction Throttle flag"}
{"level":"error","port":"9000","ip":"127.0.0.1","error":"gas limit reached","txThrottleFlag":"Select","caller":"/Users/dennis.won/go/src/github.com/harmony-one/harmony/node/worker/worker.go:127","time":"2019-08-07T13:28:33-07:00","message":"Transaction Throttle flag"}

## TODO

TxPool integration with filter module

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by denniswon** [comment]
This PR is a redo of https://github.com/harmony-one/harmony/pull/1299. (git history being messed up, so was easier this way)

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by denniswon** [comment]
Plan changed: Synced offline with @astralblue on how cross-block/time-series based tx throttling should be handled. WIP. cc: @LeoHChen @mikedoan @rlan35

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by denniswon** [comment]
the changes in this pr already in master branch (merged from r3)

**Pull request closed without merging**
