### PR TITLE
[Rosetta]Implement the /call endpoint

### PR DESCRIPTION
**Pull request by renlulu**
## Issue

#3428 

### Unit Test Coverage

Before:

```
?   	github.com/harmony-one/harmony/rosetta	[no test files]
ok  	github.com/harmony-one/harmony/rosetta/common	(cached)	coverage: 41.4% of statements
ok  	github.com/harmony-one/harmony/rosetta/services	0.217s	coverage: 43.8% of statements
```

After:

```
?   	github.com/harmony-one/harmony/rosetta	[no test files]
ok  	github.com/harmony-one/harmony/rosetta/common	(cached)	coverage: 41.4% of statements
ok  	github.com/harmony-one/harmony/rosetta/services	0.190s	coverage: 39.6% of statements
```

## Operational Checklist

1. **Does this PR introduce backward-incompatible changes to the on-disk data structure and/or the over-the-wire protocol?**. (If no, skip to question 8.)

   No

2. **Describe the migration plan.**. For each flag epoch, describe what changes take place at the flag epoch, the anticipated interactions between upgraded/non-upgraded nodes, and any special operational considerations for the migration.

3. **Describe how the plan was tested.**

4. **How much minimum baking period after the last flag epoch should we allow on Pangaea before promotion onto mainnet?**

5. **What are the planned flag epoch numbers and their ETAs on Pangaea?**

6. **What are the planned flag epoch numbers and their ETAs on mainnet?**

    Note that this must be enough to cover baking period on Pangaea.

7. **What should node operators know about this planned change?**

8. **Does this PR introduce backward-incompatible changes *NOT* related to on-disk data structure and/or over-the-wire protocol?** (If no, continue to question 11.)

    No

9. **Does the existing `node.sh` continue to work with this change?**

10. **What should node operators know about this change?**

11. **Does this PR introduce significant changes to the operational requirements of the node software, such as >20% increase in CPU, memory, and/or disk usage?**

  No

### CODE REVIEW

**Comment by renlulu** [comment]
API test: https://gist.github.com/renlulu/190b9ddc6df32910a542ca525baca442

**Comment by LeoHChen** [comment]
LGTM in general. please also add the /call end point test in the harmony-test repo to complete this PR.

**Comment by renlulu** [comment]
> LGTM in general. please also add the /call end point test in the harmony-test repo to complete this PR.

Hmm there is no construction APIs for this PR, so there is no need for Rosetta-cli automated testing, but we do need some tests similar as rpc tests in harmony-test repo in theory. The only issue is there is no python sdk for Rosetta for now : (

**Comment by LuttyYang** [comment]
LGTM

**Review by LeoHChen — APPROVED** [review]

**Comment by LeoHChen** [comment]
Hi, @renlulu , would you please rebase the code on the top of the tree and clean up the commit messages? I can merge after that.

**Review by LeoHChen — APPROVED** [review]

**Pull request merged**
