### PR TITLE
[tracer][rpc] go version of "trace_block"

### PR DESCRIPTION
**Pull request by peekpi**
## Issue

Explorer and some other products need a faster `trace_block` RPC.
The original trace_block calls a JS VM, which is too slow for products, so I rewrite the RPC in pure go language.

## Test

Before:

trace 100 blocks take around 30s

After:

trace 100 blocks take around 4s

### Test Script

```javascript

const Web3 = require('web3')

//const nodeurl = 'https://api.harmony.one'
const nodeurl = 'http://64.227.106.149:9500'

const web3 = new Web3(nodeurl)
web3.extend({
    property: 'trace',
    methods: [{
        name: 'block',
        call: 'trace_block',
        params: 1,
        inputFormatter: [web3.utils.numberToHex]
    }]
});
Time = ()=>Number(new Date())/1000

async function batchMain() {
    const latest = await web3.eth.getBlockNumber()
    console.log(latest)
    return new Promise((resolve, reject)=>{
        const result = []
        const batch = new web3.BatchRequest();
        for(let i = 100; i > 0; i--){
            const bno = latest - i;
            batch.add(web3.trace.block.request(bno, (err, res)=>{
                if(err) console.error(err)
                result.push(res)
                if(i == 1) resolve(result)
            }));
        }
        batch.execute();
    })
}

const time = ()=>Number(new Date())/1000

async function main() {
    const start = time()
    const r = await batchMain()
    console.log("main:", r.length, r.reduce((t,b)=>t+b.length, 0), time()-start)
}

main()

```

## Operational Checklist

1. **Does this PR introduce backward-incompatible changes to the on-disk data structure and/or the over-the-wire protocol?**. (If no, skip to question 8.)

    **NO**

8. **Does this PR introduce backward-incompatible changes *NOT* related to on-disk data structure and/or over-the-wire protocol?** (If no, continue to question 11.)

    **NO**

11. **Does this PR introduce significant changes to the operational requirements of the node software, such as >20% increase in CPU, memory, and/or disk usage?**

     **NO**

### CODE REVIEW

**Review by LeoHChen — APPROVED** [review]
LGTM, have you tested it with @hypnagonia ? what's blocking it ?

**Review by rlan35 — APPROVED** [review]

**Comment by rlan35** [comment]
we can merge once it's tested.

**Comment by peekpi** [comment]
> LGTM, have you tested it with @hypnagonia ? what's blocking it ?

not yet, this RPC requires an archival node. the original trace_block calls a JS VM, which is too slow for products.

**Comment by LeoHChen** [comment]
> > LGTM, have you tested it with @hypnagonia ? what's blocking it ?
> 
> not yet, testing this RPC requires an archival node. the original trace_block calls a JS VM, which is too slow for products.

@hypnagonia has an archival node dedicated for his indexer testing.  Please test it with him and get this merged asap. Thanks.

**Pull request merged**
