### PR TITLE
Comment out "Dumping block" message

### PR DESCRIPTION
**Pull request by nyetwurk**
When running explorer, every time we restart it, this dumps megabytes of
messages into zerolog, overwhelming logstash.

This is already merged into master but never got pulled into s3.

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by nyetwurk** [comment]
Can this be merged before the 1/20 update?

**Comment by LeoHChen** [comment]
@nyetwurk , merging it.

**Pull request merged**
