### PR TITLE
add number of pending cross-shard

### PR DESCRIPTION
**Pull request by LuttyYang**
## Issue

https://github.com/harmony-one/watchdog/issues/31

## Operational Checklist

1. **Does this PR introduce backward-incompatible changes to the on-disk data structure and/or the over-the-wire protocol?**. (If no, skip to question 8.)

   NO

8. **Does this PR introduce backward-incompatible changes *NOT* related to on-disk data structure and/or over-the-wire protocol?** (If no, continue to question 11.)

    NO

11. **Does this PR introduce significant changes to the operational requirements of the node software, such as >20% increase in CPU, memory, and/or disk usage?**

  NO

### CODE REVIEW

**Comment by jhd2best** [comment]
these changes are creating for this issue: https://github.com/harmony-one/watchdog/issues/31

**Comment by jhd2best** [comment]
**TEST LOGS**
try to get count of pending crosslinks
```bash
curl --location --request POST 'http://127.0.0.1:9500' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "hmy_getNumPendingCrossLinks",
    "params": [],
    "id": 1
}'
```
get response
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": 1000
}
```

try to get count of pending CX receipts
```bash
curl --location --request POST 'http://127.0.0.1:9500' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "hmy_getNumPendingCXReceipts",
    "params": [],
    "id": 1
}'
```
get response
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": 15
}
```

seems interface works well. but the rationality of the quantity needs to be checked again @LeoHChen

**Comment by sophoah** [comment]
@LeoHChen should we get that into v2 api ? api.hmny.io doesn't have any reference to v1. cc @jhd2best

**Review by rlan35 — APPROVED** [review]

**Comment by jhd2best** [comment]
> @LeoHChen should we get that into v2 api ? api.hmny.io doesn't have any reference to v1. cc @jhd2best



> @LeoHChen should we get that into v2 api ? api.hmny.io doesn't have any reference to v1. cc @jhd2best

hey soph. i have checked with Leo. because the original method(hmy_getPendingCXReceipts) is in v1, this change is an extension of the original method, so it is also placed in v1. At the same time, we have not abandoned v1, it will exist for a long time

**Pull request merged**
