### PR TITLE
change gob based serialization to protobuf #752

### PR DESCRIPTION
**Pull request by lzxm160**
work on #752

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by lzxm160** [comment]
> Jenkins, test this please.

can I see those errors from test failed?

**Comment by LeoHChen** [comment]
@lzxm160 , the error message

```
=== RUN   TestString
--- FAIL: TestString (0.00s)
    pingpong_test.go:55: expect: ping:Validator/1=>127.0.0.1:9999/[120 1 130 197 30 202 78 236 84 249 5 230 132 208 242 242 246 63 100 123 96 11 211 228 4 56 64 94 57 133 3 226 254 222 231 160 178 81 252 205 40 28 45 2 90 74 207 15 68 86 138 68 143 176 221 161 108 105 133 6 64 121 92 25 134 255 9 209 156 209 119 187 13 160 23 147 240 24 196 152 100 20 163 51 118 45 100 26 179 227 184 166 147 113 50 139], got: {1 IP:"127.0.0.1" Port:"9999" PubKey:"x\001\202\305\036\312N\354T\371\005\346\204\320\362\362\366?d{`\013\323\344\0048@^9\205\003\342\376\336\347\240\262Q\374\315(\034-\002ZJ\317\017DV\212D\217\260\335\241li\205\006@y\\\031\206\377\t\321\234\321w\273\r\240\027\223\360\030\304\230d\024\2433v-d\032\263\343\270\246\223q2\213" PeerID:"<peer.ID >"  {} [] 0}
    pingpong_test.go:62: expect: ping:Client/1=>127.0.0.1:9999/[120 1 130 197 30 202 78 236 84 249 5 230 132 208 242 242 246 63 100 123 96 11 211 228 4 56 64 94 57 133 3 226 254 222 231 160 178 81 252 205 40 28 45 2 90 74 207 15 68 86 138 68 143 176 221 161 108 105 133 6 64 121 92 25 134 255 9 209 156 209 119 187 13 160 23 147 240 24 196 152 100 20 163 51 118 45 100 26 179 227 184 166 147 113 50 139], got: {1 IP:"127.0.0.1" Port:"9999" PubKey:"x\001\202\305\036\312N\354T\371\005\346\204\320\362\362\366?d{`\013\323\344\0048@^9\205\003\342\376\336\347\240\262Q\374\315(\034-\002ZJ\317\017DV\212D\217\260\335\241li\205\006@y\\\031\206\377\t\321\234\321w\273\r\240\027\223\360\030\304\230d\024\2433v-d\032\263\343\270\246\223q2\213" Role:1 PeerID:"<peer.ID >"  {} [] 0}
    pingpong_test.go:69: expect: pong:1=>length:2, got: {0 1 [IP:"127.0.0.1" Port:"8888" PubKey:"x\001\202\305\036\312N\354T\371\005\346\204\320\362\362\366?d{`\013\323\344\0048@^9\205\003\342\376\336\347\240\262Q\374\315(\034-\002ZJ\317\017DV\212D\217\260\335\241li\205\006@y\\\031\206\377\t\321\234\321w\273\r\240\027\223\360\030\304\230d\024\2433v-d\032\263\343\270\246\223q2\213" PeerID:"<peer.ID >"  IP:"127.0.0.1" Port:"9999" PubKey:"\030\346Oc\323\250\030\026\252\324\332\327\027\363_\014 0\013\221f\272\036;{P\3143b\224\016)\350\016\234 ^\213\341\2146\010\312%\204\034\353\003\366Nu\320I\302|\340\357J\347\222\333\207\004\"x3\027\334\304\362\224\211\016\305:\354x\334,\262\377\016\226\361\217\024o\020\334\271h\233\"\020\342\231" PeerID:"<peer.ID >" ] [[120 1 130 197 30 202 78 236 84 249 5 230 132 208 242 242 246 63 100 123 96 11 211 228 4 56 64 94 57 133 3 226 254 222 231 160 178 81 252 205 40 28 45 2 90 74 207 15 68 86 138 68 143 176 221 161 108 105 133 6 64 121 92 25 134 255 9 209 156 209 119 187 13 160 23 147 240 24 196 152 100 20 163 51 118 45 100 26 179 227 184 166 147 113 50 139] [24 230 79 99 211 168 24 22 170 212 218 215 23 243 95 12 32 48 11 145 102 186 30 59 123 80 204 51 98 148 14 41 232 14 156 32 94 139 225 140 54 8 202 37 132 28 235 3 246 78 117 208 73 194 124 224 239 74 231 146 219 135 4 34 120 51 23 220 196 242 148 137 14 197 58 236 120 220 44 178 255 14 150 241 143 20 111 16 220 185 104 155 34 16 226 153]] [139 119 32 147 13 66 239 141 21 64 14 149 74 95 177 100 183 92 186 127 70 219 94 145 248 81 106 109 56 75 170 16 76 4 3 165 41 40 49 169 76 111 123 243 157 224 100 1 213 225 81 225 155 188 169 103 147 120 198 235 238 46 53 119 109 3 210 40 208 145 47 101 201 130 188 50 53 46 151 168 64 71 249 191 214 140 152 136 77 129 247 243 123 30 20 135] {} [] 0}
=== RUN   TestSerialize
--- FAIL: TestSerialize (0.00s)
    pingpong_test.go:85: Serialize/Deserialze Ping Message Failed
    pingpong_test.go:101: Serialize/Deserialze Pong Message Failed
FAIL
FAIL	github.com/harmony-one/harmony/api/proto/discovery	0.097s
```

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by lzxm160** [comment]
> @lzxm160 , the error message
> 
> ```
> === RUN   TestString
> --- FAIL: TestString (0.00s)
>     pingpong_test.go:55: expect: ping:Validator/1=>127.0.0.1:9999/[120 1 130 197 30 202 78 236 84 249 5 230 132 208 242 242 246 63 100 123 96 11 211 228 4 56 64 94 57 133 3 226 254 222 231 160 178 81 252 205 40 28 45 2 90 74 207 15 68 86 138 68 143 176 221 161 108 105 133 6 64 121 92 25 134 255 9 209 156 209 119 187 13 160 23 147 240 24 196 152 100 20 163 51 118 45 100 26 179 227 184 166 147 113 50 139], got: {1 IP:"127.0.0.1" Port:"9999" PubKey:"x\001\202\305\036\312N\354T\371\005\346\204\320\362\362\366?d{`\013\323\344\0048@^9\205\003\342\376\336\347\240\262Q\374\315(\034-\002ZJ\317\017DV\212D\217\260\335\241li\205\006@y\\\031\206\377\t\321\234\321w\273\r\240\027\223\360\030\304\230d\024\2433v-d\032\263\343\270\246\223q2\213" PeerID:"<peer.ID >"  {} [] 0}
>     pingpong_test.go:62: expect: ping:Client/1=>127.0.0.1:9999/[120 1 130 197 30 202 78 236 84 249 5 230 132 208 242 242 246 63 100 123 96 11 211 228 4 56 64 94 57 133 3 226 254 222 231 160 178 81 252 205 40 28 45 2 90 74 207 15 68 86 138 68 143 176 221 161 108 105 133 6 64 121 92 25 134 255 9 209 156 209 119 187 13 160 23 147 240 24 196 152 100 20 163 51 118 45 100 26 179 227 184 166 147 113 50 139], got: {1 IP:"127.0.0.1" Port:"9999" PubKey:"x\001\202\305\036\312N\354T\371\005\346\204\320\362\362\366?d{`\013\323\344\0048@^9\205\003\342\376\336\347\240\262Q\374\315(\034-\002ZJ\317\017DV\212D\217\260\335\241li\205\006@y\\\031\206\377\t\321\234\321w\273\r\240\027\223\360\030\304\230d\024\2433v-d\032\263\343\270\246\223q2\213" Role:1 PeerID:"<peer.ID >"  {} [] 0}
>     pingpong_test.go:69: expect: pong:1=>length:2, got: {0 1 [IP:"127.0.0.1" Port:"8888" PubKey:"x\001\202\305\036\312N\354T\371\005\346\204\320\362\362\366?d{`\013\323\344\0048@^9\205\003\342\376\336\347\240\262Q\374\315(\034-\002ZJ\317\017DV\212D\217\260\335\241li\205\006@y\\\031\206\377\t\321\234\321w\273\r\240\027\223\360\030\304\230d\024\2433v-d\032\263\343\270\246\223q2\213" PeerID:"<peer.ID >"  IP:"127.0.0.1" Port:"9999" PubKey:"\030\346Oc\323\250\030\026\252\324\332\327\027\363_\014 0\013\221f\272\036;{P\3143b\224\016)\350\016\234 ^\213\341\2146\010\312%\204\034\353\003\366Nu\320I\302|\340\357J\347\222\333\207\004\"x3\027\334\304\362\224\211\016\305:\354x\334,\262\377\016\226\361\217\024o\020\334\271h\233\"\020\342\231" PeerID:"<peer.ID >" ] [[120 1 130 197 30 202 78 236 84 249 5 230 132 208 242 242 246 63 100 123 96 11 211 228 4 56 64 94 57 133 3 226 254 222 231 160 178 81 252 205 40 28 45 2 90 74 207 15 68 86 138 68 143 176 221 161 108 105 133 6 64 121 92 25 134 255 9 209 156 209 119 187 13 160 23 147 240 24 196 152 100 20 163 51 118 45 100 26 179 227 184 166 147 113 50 139] [24 230 79 99 211 168 24 22 170 212 218 215 23 243 95 12 32 48 11 145 102 186 30 59 123 80 204 51 98 148 14 41 232 14 156 32 94 139 225 140 54 8 202 37 132 28 235 3 246 78 117 208 73 194 124 224 239 74 231 146 219 135 4 34 120 51 23 220 196 242 148 137 14 197 58 236 120 220 44 178 255 14 150 241 143 20 111 16 220 185 104 155 34 16 226 153]] [139 119 32 147 13 66 239 141 21 64 14 149 74 95 177 100 183 92 186 127 70 219 94 145 248 81 106 109 56 75 170 16 76 4 3 165 41 40 49 169 76 111 123 243 157 224 100 1 213 225 81 225 155 188 169 103 147 120 198 235 238 46 53 119 109 3 210 40 208 145 47 101 201 130 188 50 53 46 151 168 64 71 249 191 214 140 152 136 77 129 247 243 123 30 20 135] {} [] 0}
> === RUN   TestSerialize
> --- FAIL: TestSerialize (0.00s)
>     pingpong_test.go:85: Serialize/Deserialze Ping Message Failed
>     pingpong_test.go:101: Serialize/Deserialze Pong Message Failed
> FAIL
> FAIL	github.com/harmony-one/harmony/api/proto/discovery	0.097s
> ```

see,I'll try fix it later

**Pull request closed without merging**
