### PR TITLE
[misc] remove unused flag in harmony

### PR DESCRIPTION
**Pull request by LeoHChen**
Signed-off-by: Leo Chen <leo@harmony.one>

### CODE REVIEW

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by alajko** [comment]
@LeoHChen  This simple change is not going to pass Jenkins because corresponding script on Jenkins side expects this flag to be present. 
You can see that the error is:
`2019/04/16 23:14:32 Stderr flag provided but not defined: -is_leader` on Jenkins.

**Comment by LeoHChen** [comment]
> @LeoHChen This simple change is not going to pass Jenkins because corresponding script on Jenkins side expects this flag to be present.
> You can see that the error is:
> `2019/04/16 23:14:32 Stderr flag provided but not defined: -is_leader` on Jenkins.

En. I've fixed the deploy script.

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Pull request merged**
