### PR TITLE
disable toShardID as it was not used yet

### PR DESCRIPTION
**Pull request by mikedoan**
disable toShardID as it was not used yet

### CODE REVIEW

**Comment by LeoHChen** [comment]
why can't we add it in SDK?  I don't think we should keep adding testing and demo code in the code base.  We are building a production system.

**Comment by mikedoan** [comment]
Search ToShardID in our code. it's not used anywhere. I guess it will be used for cross shard transaction.

**Comment by neeboo** [comment]
Please make decision on that. If already added, dont remove then.

**Comment by LeoHChen** [comment]
we won't remove it.  For now, this parameter is not used yet.

**Comment by neeboo** [comment]
> we won't remove it. For now, this parameter is not used yet.
> […](#)

Currently I have added it to latest sdk version. It is a breaking change for Transaction rlp signing. So please be careful adding or removing some field here.

**Pull request closed without merging**
