### PR TITLE
Fix for consensus stuck.

### PR DESCRIPTION
**Pull request by Frozen**
We can see that error happened on `onNewView`:

`{"level":"warn","myBlock":33980416,"myViewID":33984024,"phase":"Commit","mode":"ViewChanging","error":"Block verification failed: crosslink already exist","caller":"/home/sp/harmony/harmony/consen
sus/view_change.go:496","time":"2022-11-15T05:44:05.852088781Z","message":"[onNewView] Verify New View Msg Failed"}`

`onNewView` is final step of view change mechanism, and block is already invalid. Previous step is `startNewView`, so i added check there for no unchecked blocks sending.

### CODE REVIEW

**Comment by sophoah** [comment]
@Frozen could you update the PR description explaining the why, how, this PR help.

**Comment by ONECasey** [comment]
I agree with @sophoah. All my tests and local deployments work well with this change but still a little confused about how this fixes the issue.

**Comment by MaxMustermann2** [comment]
Can you perhaps provide an example to reproduce the issue in localnet? You suggestion on Notion that the bug can be replicated by creating "empty blocks to send".

**Comment by Frozen** [comment]
I can't reproduce same error on localnet.

**Review by MaxMustermann2 — APPROVED** [review]

**Comment by Frozen** [comment]
Starts new view change if block invalid.

**Review by MaxMustermann2 — APPROVED** [review]

**Pull request merged**
