### PR TITLE
[test] reduce local cx test to 1 to speed up the test

### PR DESCRIPTION
**Pull request by LeoHChen**
Signed-off-by: Leo Chen <leo@harmony.one>

### CODE REVIEW

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by fxfactorial** [comment]
Jenkins, test this please

**Comment by fxfactorial** [comment]
Jenkins, test this please

**Comment by LeoHChen** [comment]
close for now, needs @Daniel-VDM 's fix on the test.

**Pull request closed without merging**
