### PR TITLE
Staking types test

### PR DESCRIPTION
**Pull request by JackyWYX**
## Issue And Description

This is part of the issue [#2498](https://github.com/harmony-one/harmony/pull/2498). 

* Refactored some unit test cases for `staking/types`
* Added unit test cases for module `staking/types`

### Unit Test Coverage

Before:

```
PASS
coverage: 52.2% of statements
ok      github.com/harmony-one/harmony/staking/types    0.222s
```

After:

```
PASS
coverage: 65.8% of statements
ok      github.com/harmony-one/harmony/staking/types    0.382s
```

### CODE REVIEW

**Comment by JackyWYX** [comment]
Jenkins, test this please

**Comment by JackyWYX** [comment]
Jenkins, test this please

**Comment by rlan35** [comment]
Jenkins, test this please

**Comment by rlan35** [comment]
good job!

**Pull request merged**
