### PR TITLE
Log blockEpoch and blockNumber as Uint64 not Str

### PR DESCRIPTION
**Pull request by nyetwurk**
Fix issue #1333

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by nyetwurk** [comment]
jenkins, test this please.

**Comment by nyetwurk** [comment]
retest this please

**Comment by xChickens** [comment]
test this please

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by xChickens** [comment]
Didn't you already merge this into r3? If you put the change in r3 it will be merged into master soon anyways.

**Comment by nyetwurk** [comment]
yea i forgot to close this PR. Not sure what the right branch to submit prs against is... ill try to constrain it to one branch once i know which one ;) Apologies for the thrashing

**Pull request closed without merging**
