### PR TITLE
Broadcast vote power.

### PR DESCRIPTION
**Pull request by Frozen**
Leader broadcasts vote power, all others receive numbers and store. It available to receive throw api method `GetLastSigningPower`.

### CODE REVIEW

**Comment by mur-me** [comment]
Thanks for the fix, @Frozen  

---

I've tested the following scenario:
1. Spin up localnet
**Result:** Sing power == 68%
2. Kill any internal node to loose consensus, e.x. current leader.
3. Check the signing power via `hmy_getLastSigningPower`
**Result:** signing power was 60%
```
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": 1, "method": "hmy_getLastSigningPower","params": []}' 127.0.0.1:9610
{"jsonrpc":"2.0","id":1,"result":0.6}
```
6. Restart killed node, wait until it rejoin consensus.
**Result:** Sing power is again == 68%, consensus has been restored 
```
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": 1, "method": "hmy_getLastSigningPower","params": []}' 127.0.0.1:9600
{"jsonrpc":"2.0","id":1,"result":0.68}
```

**Comment by mur-me** [comment]
rn, blockchain couldn't spin up in RPC/Rosseta tests due to:
```json
{
    "level": "error",
    "port": "9000",
    "ip": "127.0.0.1",
    "error": "cannot finalize block: Timeout waiting for commit sigs for reward calculation",
    "caller": "/go/src/github.com/harmony-one/harmony/consensus/consensus_block_proposing.go:236",
    "time": "2024-09-06T09:40:39.249311887Z",
    "message": "[ProposeNewBlock] Failed finalizing the new block"
}

```

**Comment by sophoah** [comment]
@Frozen you latest rebase/conflict fix broke consensus on localnet. Please check

**Comment by Frozen** [comment]
> @Frozen you latest rebase/conflict fix broke consensus on localnet. Please check

Rebase on latest dev broke consensus. Fixed

**Comment by mur-me** [comment]
> Thanks for the fix, @Frozen
> 
> I've tested the following scenario:
> 
>     1. Spin up localnet
>        **Result:** Sing power == 68%
> 
>     2. Kill any internal node to loose consensus, e.x. current leader.
> 
>     3. Check the signing power via `hmy_getLastSigningPower`
>        **Result:** signing power was 60%
> 
> 
> ```
> curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": 1, "method": "hmy_getLastSigningPower","params": []}' 127.0.0.1:9610
> {"jsonrpc":"2.0","id":1,"result":0.6}
> ```
> 
>     6. Restart killed node, wait until it rejoin consensus.
>        **Result:** Sing power is again == 68%, consensus has been restored
> 
> 
> ```
> curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": 1, "method": "hmy_getLastSigningPower","params": []}' 127.0.0.1:9600
> {"jsonrpc":"2.0","id":1,"result":0.68}
> ```

Rechecked the same scenario as mentioned above on both shards with external validator:
* signPower dropped bellow 67, e.x. 54
* restored one of the validators
* signPower went to the > 67 and new blocks have started to be created
Result: PASSED :heavy_check_mark:

**Comment by sophoah** [comment]
@Frozen please fix rebase and fix conflict with latest dev

**Comment by Frozen** [comment]
Rebased

**Comment by sophoah** [comment]
just finish testing this one with the latest rebase. All good for me. Good job @Frozen

**Review by GheisMohammadi — APPROVED** [review]

**Review by sophoah — APPROVED** [review]

**Pull request merged**
