### PR TITLE
Expand slashing unit testing

### PR DESCRIPTION
**Pull request by denniswon**
## Issue

https://github.com/harmony-one/harmony/issues/2330

## Test

go test -timeout 30s github.com/harmony-one/harmony/staking/slash -run ^(TestXPercentSlashed)$

ok  	github.com/harmony-one/harmony/staking/slash	0.503s
Success: Tests passed.

### CODE REVIEW

**Comment by fxfactorial** [comment]
Yes , correct approach

**Comment by denniswon** [comment]
synced up with @fxfactorial offline. This PR should be good to merge in terms of test cases covered, but a follow up pr will be made to close the issue (description) for semi-integration test level test case for validating the state change of slashing done block.

**Comment by fxfactorial** [comment]
I think you messed up the force push, look at the files changed for the PR, only two lines changed and its whitespace.

**Comment by denniswon** [comment]
@fxfactorial my apology. should have checked after I pushed force. I updated it.

**Pull request merged**
