### PR TITLE
Change Byte Output in Zerolog to Hex

### PR DESCRIPTION
**Pull request by charleszqwang**
-Also Some Conversion from Log15 to Zerolog

### CODE REVIEW

**Comment by charleszqwang** [comment]
test this please

**Comment by nyetwurk** [comment]
Similar to https://github.com/harmony-one/harmony/pull/1506

**Comment by xChickens** [comment]
It's the same, he just doesn't know how to trigger Jenkins.

**Comment by xChickens** [comment]
Jenkins, test this please.

**Comment by xChickens** [comment]
Jenkins test this please PLEASE, FOR THE LOVE GOD TEST THIS PLEASE

**Pull request merged**
