### PR TITLE
support fetching pending txns in rpc

### PR DESCRIPTION
**Pull request by rlan35**

### CODE REVIEW

**Comment by sophoah** [comment]
localnet test result :
```
node websocket-PR3892.js 
0x3a74a5a299b8b19ceb22007490592794

0x93622a04441b6b0bff538105e2868f00518d665c3087b81f0fa7da962bbb76fc
0x93622a04441b6b0bff538105e2868f00518d665c3087b81f0fa7da962bbb76fc
{
  blockHash: null,
  blockNumber: null,
  from: '0x80E8be4629FE450AEA125E0B63BA663D9913E411',
  gas: 21000,
  gasPrice: '1000000000',
  hash: '0xb37d1a5dea91841d1335d9aa1610ef79d372842f245657a32a7fdd8f45f5fd34',
  input: '0x',
  nonce: 0,
  r: '0xe97015a0546d681156ae5c85fe520003399357c12208e8858cb9bd52bf62e896',
  s: '0x31ba322c4addc944b8da2eccb573369324d68ef133a911d2fc2cf084acea8f78',
  timestamp: '0x0',
  to: '0x514650ca30B3c79f693e14220115434236D44aEB',
  transactionIndex: null,
  v: '0x27',
  value: '2000000000000000000'
  ```

**Comment by sophoah** [comment]
finalized block:
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "blockHash": "0x4380ab0e0f2c9e44c5c6e6fafbbe398d795e692eccf013d43af82203e30cffe8",
    "blockNumber": 1332,
    "ethHash": "0xb37d1a5dea91841d1335d9aa1610ef79d372842f245657a32a7fdd8f45f5fd34",
    "from": "one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7",
    "gas": 21000,
    "gasPrice": 1000000000,
    "hash": "0x93622a04441b6b0bff538105e2868f00518d665c3087b81f0fa7da962bbb76fc",
    "input": "0x",
    "nonce": 0,
    "r": "0xe97015a0546d681156ae5c85fe520003399357c12208e8858cb9bd52bf62e896",
    "s": "0x31ba322c4addc944b8da2eccb573369324d68ef133a911d2fc2cf084acea8f78",
    "shardID": 0,
    "timestamp": 1633066570,
    "to": "one129r9pj3sk0re76f7zs3qz92rggmdgjhtwge62k",
    "toShardID": 0,
    "transactionIndex": 0,
    "v": "0x27",
    "value": 2e+18
  }
}
```

**Review by sophoah — APPROVED** [review]
LGTM

**Comment by sophoah** [comment]
travis-CI build need a new image pushed for it to work. here is a local run of the tests :
```
[sp@ip-172-31-10-45 localnet]$ bash scripts/run.sh -n
~/harmony/harmony-test/localnet ~/harmony/harmony-test/localnet
~/harmony/harmony-test/localnet

=== STARTING RPC TESTS ===

~/harmony/harmony-test/localnet ~/harmony/harmony-test/localnet
building ./cmd/harmony
Harmony (C) 2020. harmony, version v7174-v4.3.0-0-g15f9b2d1 (sp@ 2021-10-02T15:47:08+0000)
building ./cmd/bootnode
Harmony (C) 2019. bootnode, version v7174-v4.3.0-0-g15f9b2d1 (sp@ 2021-10-02T15:47:08+0000)
~/go/src/github.com/harmony-one/harmony/bin ~/go/src/github.com/harmony-one/harmony
md5sum: libbls384_256.so: No such file or directory
launching boot node ...
bootnode launched. +  /ip4/127.0.0.1/tcp/19876/p2p/Qmc1V6W7BwX8Ugb42Ti8RnXF1rY5PF7nnZ6bKBryCgi6cv
skip empty node
My Genesis Account: one1spshr72utf6rwxseaz339j09ed8p6f8ke370zj/2d61379e44a772e5757e27ee2b3874254f56073e6bd226eb8b160371cc3c18b8c4977bd3dcb71fd57dc62bf0e143fd08:0
Legacy mode; node key 2d61379e44a772e5757e27ee2b3874254f56073e6bd226eb8b160371cc3c18b8c4977bd3dcb71fd57dc62bf0e143fd08; -> shard 0
My Genesis Account: one16qsd5ant9v94jrs89mruzx62h7ekcfxmduh2rx/ee2474f93cba9241562efc7475ac2721ab0899edf8f7f115a656c0c1f9ef8203add678064878d174bb478fa2e6630502:1
Legacy mode; node key ee2474f93cba9241562efc7475ac2721ab0899edf8f7f115a656c0c1f9ef8203add678064878d174bb478fa2e6630502; -> shard 1
My Genesis Account: one1d2rngmem4x2c6zxsjjz29dlah0jzkr0k2n88wc/86dc2fdc2ceec18f6923b99fd86a68405c132e1005cf1df72dca75db0adfaeb53d201d66af37916d61f079f34f21fb96:0
Legacy mode; node key 86dc2fdc2ceec18f6923b99fd86a68405c132e1005cf1df72dca75db0adfaeb53d201d66af37916d61f079f34f21fb96; -> shard 0
My Genesis Account: one1est2gxcvavmtnzc7mhd73gzadm3xxcv5zczdtw/776f3b8704f4e1092a302a60e84f81e476c212d6f458092b696df420ea19ff84a6179e8e23d090b9297dc041600bc100:1
Legacy mode; node key 776f3b8704f4e1092a302a60e84f81e476c212d6f458092b696df420ea19ff84a6179e8e23d090b9297dc041600bc100; -> shard 1
My Genesis Account: one1ghkz3frhske7emk79p7v2afmj4a5t0kmjyt4s5/eca09c1808b729ca56f1b5a6a287c6e1c3ae09e29ccf7efa35453471fcab07d9f73cee249e2b91f5ee44eb9618be3904:0
Legacy mode; node key eca09c1808b729ca56f1b5a6a287c6e1c3ae09e29ccf7efa35453471fcab07d9f73cee249e2b91f5ee44eb9618be3904; -> shard 0
My Genesis Account: one1m6m0ll3q7ljdqgmth2t5j7dfe6stykucpj2nr5/40379eed79ed82bebfb4310894fd33b6a3f8413a78dc4d43b98d0adc9ef69f3285df05eaab9f2ce5f7227f8cb920e809:1
Legacy mode; node key 40379eed79ed82bebfb4310894fd33b6a3f8413a78dc4d43b98d0adc9ef69f3285df05eaab9f2ce5f7227f8cb920e809; -> shard 1
Started Explorer server at: 0.0.0.0:5098
My Genesis Account: one1p7ht2d4kl8ve7a8jxw746yfnx4wnfxtp8jqxwe/ca86e551ee42adaaa6477322d7db869d3e203c00d7b86c82ebee629ad79cb6d57b8f3db28336778ec2180e56a8e07296:1
Legacy mode; node key ca86e551ee42adaaa6477322d7db869d3e203c00d7b86c82ebee629ad79cb6d57b8f3db28336778ec2180e56a8e07296; -> shard 1
Started RPC server at: 0.0.0.0:9598
Started Auth-RPC server at: 0.0.0.0:9599
Started WS server at: 0.0.0.0:9898
Started Rosetta server at: 0.0.0.0:9798
My Genesis Account: one12fuf7x9rgtdgqg7vgq0962c556m3p7afsxgvll/02c8ff0b88f313717bc3a627d2f8bb172ba3ad3bb9ba3ecb8eed4b7c878653d3d4faf769876c528b73f343967f74a917:0
Legacy mode; node key 02c8ff0b88f313717bc3a627d2f8bb172ba3ad3bb9ba3ecb8eed4b7c878653d3d4faf769876c528b73f343967f74a917; -> shard 0
Started RPC server at: 0.0.0.0:9516
Started Auth-RPC server at: 0.0.0.0:9517
Started WS server at: 0.0.0.0:9816
My Genesis Account: one1r4zyyjqrulf935a479sgqlpa78kz7zlcg2jfen/fc4b9c535ee91f015efff3f32fbb9d32cdd9bfc8a837bb3eee89b8fff653c7af2050a4e147ebe5c7233dc2d5df06ee0a:0
Legacy mode; node key fc4b9c535ee91f015efff3f32fbb9d32cdd9bfc8a837bb3eee89b8fff653c7af2050a4e147ebe5c7233dc2d5df06ee0a; -> shard 0
My Genesis Account: one1pdv9lrdwl0rg5vglh4xtyrv3wjk3wsqket7zxy/65f55eb3052f9e9f632b2923be594ba77c55543f5c58ee1454b9cfd658d25e06373b0f7d42a19c84768139ea294f6204:0
Legacy mode; node key 65f55eb3052f9e9f632b2923be594ba77c55543f5c58ee1454b9cfd658d25e06373b0f7d42a19c84768139ea294f6204; -> shard 0
My Genesis Account: one1a0x3d6xpmr6f8wsyaxd9v36pytvp48zckswvv9/c4e4708b6cf2a2ceeb59981677e9821eebafc5cf483fb5364a28fa604cc0ce69beeed40f3f03815c9e196fdaec5f1097:1
Legacy mode; node key c4e4708b6cf2a2ceeb59981677e9821eebafc5cf483fb5364a28fa604cc0ce69beeed40f3f03815c9e196fdaec5f1097; -> shard 1
My Genesis Account: one1ljznytjyn269azvszjlcqvpcj6hjm822yrcp2e/68ae289d73332872ec8d04ac256ca0f5453c88ad392730c5741b6055bc3ec3d086ab03637713a29f459177aaa8340615:1
Legacy mode; node key 68ae289d73332872ec8d04ac256ca0f5453c88ad392730c5741b6055bc3ec3d086ab03637713a29f459177aaa8340615; -> shard 1
Staking mode; node key 4f41a37a3a8d0695dd6edcc58142c6b7d98e74da5c90e79b587b3b960b6a4f5e048e6d8b8a000d77a478d44cd640270c; -> shard 0
My Genesis Account: one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7/678ec9670899bf6af85b877058bea4fc1301a5a3a376987e826e3ca150b80e3eaadffedad0fedfa111576fa76ded980c:0
Started RPC server at: 0.0.0.0:9512
Started Auth-RPC server at: 0.0.0.0:9513
Started WS server at: 0.0.0.0:9812
My Genesis Account: one1658znfwf40epvy7e46cqrmzyy54h4n0qa73nep/576d3c48294e00d6be4a22b07b66a870ddee03052fe48a5abbd180222e5d5a1f8946a78d55b025de21635fd743bbad90:1
Legacy mode; node key 576d3c48294e00d6be4a22b07b66a870ddee03052fe48a5abbd180222e5d5a1f8946a78d55b025de21635fd743bbad90; -> shard 1
Legacy mode; node key 678ec9670899bf6af85b877058bea4fc1301a5a3a376987e826e3ca150b80e3eaadffedad0fedfa111576fa76ded980c; -> shard 0
My Genesis Account: one1a50tun737ulcvwy0yvve0pvu5skq0kjargvhwe/52ecce5f64db21cbe374c9268188f5d2cdd5bec1a3112276a350349860e35fb81f8cfe447a311e0550d961cf25cb988d:0
Legacy mode; node key 52ecce5f64db21cbe374c9268188f5d2cdd5bec1a3112276a350349860e35fb81f8cfe447a311e0550d961cf25cb988d; -> shard 0
My Genesis Account: one1d7jfnr6yraxnrycgaemyktkmhmajhp8kl0yahv/f47238daef97d60deedbde5302d05dea5de67608f11f406576e363661f7dcbc4a1385948549b31a6c70f6fde8a391486:1
Legacy mode; node key f47238daef97d60deedbde5302d05dea5de67608f11f406576e363661f7dcbc4a1385948549b31a6c70f6fde8a391486; -> shard 1
My Genesis Account: one1658znfwf40epvy7e46cqrmzyy54h4n0qa73nep/49d15743b36334399f9985feb0753430a2b287b2d68b84495bbb15381854cbf01bca9d1d9f4c9c8f18509b2bfa6bd40f:1
Legacy mode; node key 49d15743b36334399f9985feb0753430a2b287b2d68b84495bbb15381854cbf01bca9d1d9f4c9c8f18509b2bfa6bd40f; -> shard 1
My Genesis Account: one1pf75h0t4am90z8uv3y0dgunfqp4lj8wr3t5rsp/e751ec995defe4931273aaebcb2cd14bf37e629c554a57d3f334c37881a34a6188a93e76113c55ef3481da23b7d7ab09:0
Legacy mode; node key e751ec995defe4931273aaebcb2cd14bf37e629c554a57d3f334c37881a34a6188a93e76113c55ef3481da23b7d7ab09; -> shard 0
My Genesis Account: one129r9pj3sk0re76f7zs3qz92rggmdgjhtwge62k/63f479f249c59f0486fda8caa2ffb247209489dae009dfde6144ff38c370230963d360dffd318cfb26c213320e89a512:1
Legacy mode; node key 63f479f249c59f0486fda8caa2ffb247209489dae009dfde6144ff38c370230963d360dffd318cfb26c213320e89a512; -> shard 1
My Genesis Account: one1d2rngmem4x2c6zxsjjz29dlah0jzkr0k2n88wc/16513c487a6bb76f37219f3c2927a4f281f9dd3fd6ed2e3a64e500de6545cf391dd973cc228d24f9bd01efe94912e714:0
Legacy mode; node key 16513c487a6bb76f37219f3c2927a4f281f9dd3fd6ed2e3a64e500de6545cf391dd973cc228d24f9bd01efe94912e714; -> shard 0
My Genesis Account: one1uyshu2jgv8w465yc8kkny36thlt2wvel89tcmg/a547a9bf6fdde4f4934cde21473748861a3cc0fe8bbb5e57225a29f483b05b72531f002f8187675743d819c955a86100:1
Legacy mode; node key a547a9bf6fdde4f4934cde21473748861a3cc0fe8bbb5e57225a29f483b05b72531f002f8187675743d819c955a86100; -> shard 1
Started RPC server at: 0.0.0.0:9506
Started Auth-RPC server at: 0.0.0.0:9507
Started WS server at: 0.0.0.0:9806
Started RPC server at: 0.0.0.0:9618
Started Auth-RPC server at: 0.0.0.0:9619
Started WS server at: 0.0.0.0:9918
Staking mode; node key 5e2f14abeadf0e759beb1286ed6095d9d1b2d64ad394316991161c6f95237710e0a4beda8adeaefde4844ab4c4b2bf98; -> shard 0
My Genesis Account: one1z05g55zamqzfw9qs432n33gycdmyvs38xjemyl/95117937cd8c09acd2dfae847d74041a67834ea88662a7cbed1e170350bc329e53db151e5a0ef3e712e35287ae954818:0
Legacy mode; node key 95117937cd8c09acd2dfae847d74041a67834ea88662a7cbed1e170350bc329e53db151e5a0ef3e712e35287ae954818; -> shard 0
Started RPC server at: 0.0.0.0:9600
Started Auth-RPC server at: 0.0.0.0:9601
Started RPC server at: 0.0.0.0:9504
Started Auth-RPC server at: 0.0.0.0:9505
Started RPC server at: 0.0.0.0:9502
Started Auth-RPC server at: 0.0.0.0:9503
Started WS server at: 0.0.0.0:9802
Started WS server at: 0.0.0.0:9804
Started RPC server at: 0.0.0.0:9508
Started Auth-RPC server at: 0.0.0.0:9509
Started WS server at: 0.0.0.0:9808
Started RPC server at: 0.0.0.0:9616
Started Auth-RPC server at: 0.0.0.0:9617
Started WS server at: 0.0.0.0:9916
Started RPC server at: 0.0.0.0:9612
Started Auth-RPC server at: 0.0.0.0:9613
Started WS server at: 0.0.0.0:9912
Started RPC server at: 0.0.0.0:9514
Started Auth-RPC server at: 0.0.0.0:9515
Started RPC server at: 0.0.0.0:9524
Started Auth-RPC server at: 0.0.0.0:9525
Started RPC server at: 0.0.0.0:9614
Started WS server at: 0.0.0.0:9824
Started Auth-RPC server at: 0.0.0.0:9615
Started WS server at: 0.0.0.0:9914
Started WS server at: 0.0.0.0:9814
Started RPC server at: 0.0.0.0:9518
Started RPC server at: 0.0.0.0:9510
Started Auth-RPC server at: 0.0.0.0:9519
Started RPC server at: 0.0.0.0:9522
Started Auth-RPC server at: 0.0.0.0:9523
Started WS server at: 0.0.0.0:9822
Started RPC server at: 0.0.0.0:9500
Started Auth-RPC server at: 0.0.0.0:9501
Started WS server at: 0.0.0.0:9800
Started WS server at: 0.0.0.0:9818
Started Auth-RPC server at: 0.0.0.0:9511
Started WS server at: 0.0.0.0:9810
Started RPC server at: 0.0.0.0:9608
Started Auth-RPC server at: 0.0.0.0:9609
Started WS server at: 0.0.0.0:9908
Started RPC server at: 0.0.0.0:9606
Started Auth-RPC server at: 0.0.0.0:9607
Started WS server at: 0.0.0.0:9906
Started RPC server at: 0.0.0.0:9610
Started Auth-RPC server at: 0.0.0.0:9611
Started WS server at: 0.0.0.0:9910
Started RPC server at: 0.0.0.0:9620
Started Auth-RPC server at: 0.0.0.0:9621
Started WS server at: 0.0.0.0:9920
Started RPC server at: 0.0.0.0:9604
Started Auth-RPC server at: 0.0.0.0:9605
Started WS server at: 0.0.0.0:9904
Started RPC server at: 0.0.0.0:9602
Started Auth-RPC server at: 0.0.0.0:9603
Started WS server at: 0.0.0.0:9902
Started RPC server at: 0.0.0.0:9520
Started Auth-RPC server at: 0.0.0.0:9521
Started WS server at: 0.0.0.0:9820
Started Explorer server at: 0.0.0.0:5096
Started RPC server at: 0.0.0.0:9596
Started Auth-RPC server at: 0.0.0.0:9597
Started WS server at: 0.0.0.0:9896
Started Rosetta server at: 0.0.0.0:9796
Waiting for localnet to boot...
Waiting for localnet to boot...
Waiting for localnet to boot...
Waiting for localnet to boot...
Waiting for localnet to boot...
Waiting for localnet to boot...
Waiting for localnet to boot...
Waiting for localnet to boot...
Localnet booted.
Starting test suite...
========================================================================= test session starts =========================================================================
platform linux -- Python 3.7.10, pytest-5.4.3, py-1.10.0, pluggy-0.13.1 -- /home/sp/pythonenv/bin/python3
cachedir: .pytest_cache
rootdir: /home/sp/harmony/harmony-test/localnet
plugins: forked-1.3.0, xdist-1.33.0, ordering-0.6, flaky-3.7.0
collected 60 items                                                                                                                                                    

rpc_tests/test_transaction.py::test_send_raw_transaction_v1 PASSED
rpc_tests/test_transaction.py::test_send_raw_transaction_v2 PASSED
rpc_tests/test_transaction.py::test_get_transaction_by_hash_v1 PASSED
rpc_tests/test_transaction.py::test_get_transaction_by_hash_v2 PASSED
rpc_tests/test_transaction.py::test_get_transaction_receipt_v1 PASSED
rpc_tests/test_transaction.py::test_get_transaction_receipt_v2 PASSED
rpc_tests/test_transaction.py::test_get_transaction_by_block_hash_and_index_v1 PASSED
rpc_tests/test_transaction.py::test_get_transaction_by_block_hash_and_index_v2 PASSED
rpc_tests/test_transaction.py::test_get_transaction_by_block_number_and_index_v1 PASSED
rpc_tests/test_transaction.py::test_get_transaction_by_block_number_and_index_v2 PASSED
rpc_tests/test_account.py::test_get_transactions_count send_and_confirm_transaction: PASSED
rpc_tests/test_account.py::test_get_transactions_history_v1 PASSED
rpc_tests/test_account.py::test_get_transactions_history_v2 PASSED
rpc_tests/test_account.py::test_get_balances_by_block_number_v1 PASSED
rpc_tests/test_account.py::test_get_balances_by_block_number_v2 PASSED
rpc_tests/test_blockchain.py::test_invalid_method PASSED
rpc_tests/test_blockchain.py::test_net_peer_count_v1 PASSED
rpc_tests/test_blockchain.py::test_net_peer_count_v2 PASSED
rpc_tests/test_blockchain.py::test_get_node_metadata PASSED
rpc_tests/test_blockchain.py::test_get_sharding_structure PASSED
rpc_tests/test_blockchain.py::test_get_latest_header PASSED
rpc_tests/test_blockchain.py::test_get_latest_chain_headers PASSED
rpc_tests/test_blockchain.py::test_get_leader_address PASSED
rpc_tests/test_blockchain.py::test_get_block_signer_keys PASSED
rpc_tests/test_blockchain.py::test_get_header_by_number PASSED
rpc_tests/test_blockchain.py::test_get_block_signers PASSED
rpc_tests/test_blockchain.py::test_get_block_number_v1 PASSED
rpc_tests/test_blockchain.py::test_get_block_number_v2 PASSED
rpc_tests/test_blockchain.py::test_get_epoch_v1 PASSED
rpc_tests/test_blockchain.py::test_get_epoch_v2 PASSED
rpc_tests/test_blockchain.py::test_get_gas_price_v1 PASSED
rpc_tests/test_blockchain.py::test_get_gas_price_v2 PASSED
rpc_tests/test_blockchain.py::test_get_protocol_version_v1 PASSED
rpc_tests/test_blockchain.py::test_get_protocol_version_v2 PASSED
rpc_tests/test_blockchain.py::test_get_block_transaction_count_by_number_v1 PASSED
rpc_tests/test_blockchain.py::test_get_block_transaction_count_by_number_v2 PASSED
rpc_tests/test_blockchain.py::test_get_block_transaction_count_by_hash_v1 PASSED
rpc_tests/test_blockchain.py::test_get_block_transaction_count_by_hash_v2 PASSED
rpc_tests/test_blockchain.py::test_get_block_by_number_v1 PASSED
rpc_tests/test_blockchain.py::test_get_block_by_number_v2 PASSED
rpc_tests/test_blockchain.py::test_get_blocks_v1 PASSED
rpc_tests/test_blockchain.py::test_get_blocks_v2 PASSED
rpc_tests/test_blockchain.py::test_get_block_by_hash_v1 PASSED
rpc_tests/test_blockchain.py::test_get_block_by_hash_v2 PASSED
rpc_tests/test_contract.py::test_call_v1 send_and_confirm_transaction: PASSED
rpc_tests/test_contract.py::test_call_v2 PASSED
rpc_tests/test_contract.py::test_estimate_gas_v1 SKIPPED
rpc_tests/test_contract.py::test_estimate_gas_v2 SKIPPED
rpc_tests/test_contract.py::test_get_code_v1 PASSED
rpc_tests/test_contract.py::test_get_code_v2 PASSED
rpc_tests/test_contract.py::test_get_storage_at_v1 PASSED
rpc_tests/test_contract.py::test_get_storage_at_v2 PASSED
rpc_tests/test_transaction.py::test_get_pool_stats PASSED
rpc_tests/test_transaction.py::test_get_current_transaction_error_sink PASSED
rpc_tests/test_transaction.py::test_resend_cx send_and_confirm_transaction: PASSED
rpc_tests/test_transaction.py::test_get_pending_cx_receipts SKIPPED
rpc_tests/test_transaction.py::test_get_cx_receipt_by_hash_v1 PASSED
rpc_tests/test_transaction.py::test_get_cx_receipt_by_hash_v2 PASSED
rpc_tests/test_transaction.py::test_pending_transactions_v1 PASSED
rpc_tests/test_transaction.py::test_pending_transactions_v2 PASSED
===Flaky Test Report===

test_get_block_signer_keys passed 1 out of the required 1 times. Success!
test_get_block_signers passed 1 out of the required 1 times. Success!
test_resend_cx passed 1 out of the required 1 times. Success!
test_get_pending_cx_receipts failed (5 runs remaining out of 6).
        <class 'AssertionError'>
        Expected key 'shard-id' in {
  "difficulty": "0x0",
  "epoch": 2,
  "extraData": "0x",
  "gasLimit": "0x4c4b400",
  "gasUsed": "0x5208",
  "hash": "0x5a49ca36d7b93d1300ee7078e9c3e2c9b71306b0b348663a2b8ced65c7862035",
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "miner": "0x6911b75b2560be9a8f71164a33086be4511fc99a",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "nonce": "0x0000000000000000",
  "number": "0x12",
  "parentHash": "0x5ce534f9ff337e148243c204238d8e03253bba817e06256d7d9d3e3dc8e215dd",
  "receiptsRoot": "0x056b23fbba480696b65fe5a59b8f2148a1299103c4f57df839233af2cf4ca2d2",
  "sha3Uncles": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "shardID": 0,
  "stateRoot": "0xd2c8e3bcf51d52fbf7c060d7c70a9d85bcda07cde0c65a0cea54de7e00b93c25",
  "timestamp": "0x61587f76",
  "transactionsRoot": "0x3a0ba08bb7a2912a001fc09187057375e19ab005f360e11a9b8b0f432581db24",
  "viewID": 18
}
        [<TracebackEntry /home/sp/harmony/harmony-test/localnet/rpc_tests/test_transaction.py:260>, <TracebackEntry /home/sp/harmony/harmony-test/localnet/rpc_tests/utils.py:72>, <TracebackEntry /home/sp/harmony/harmony-test/localnet/rpc_tests/utils.py:76>, <TracebackEntry /home/sp/harmony/harmony-test/localnet/rpc_tests/utils.py:75>]
test_get_cx_receipt_by_hash_v1 passed 1 out of the required 1 times. Success!
test_get_cx_receipt_by_hash_v2 passed 1 out of the required 1 times. Success!

===End Flaky Test Report===

======================================================================= short test summary info =======================================================================
SKIPPED [1] /home/sp/harmony/harmony-test/localnet/rpc_tests/test_contract.py:124: Traceback (most recent call last):
  File "/home/sp/harmony/harmony-test/localnet/rpc_tests/test_contract.py", line 121, in test_estimate_gas_v1
    response = check_and_unpack_rpc_response(raw_response, expect_error=False)
  File "/home/sp/harmony/harmony-test/localnet/rpc_tests/utils.py", line 98, in check_and_unpack_rpc_response
    assert "result" in response.keys(), f"Expected result in RPC response: {json.dumps(response, indent=2)}"
AssertionError: Expected result in RPC response: {
  "jsonrpc": "2.0",
  "id": "1",
  "error": {
    "code": -32000,
    "message": "out of gas"
  }
}
SKIPPED [1] /home/sp/harmony/harmony-test/localnet/rpc_tests/test_contract.py:138: Traceback (most recent call last):
  File "/home/sp/harmony/harmony-test/localnet/rpc_tests/test_contract.py", line 135, in test_estimate_gas_v2
    response = check_and_unpack_rpc_response(raw_response, expect_error=False)
  File "/home/sp/harmony/harmony-test/localnet/rpc_tests/utils.py", line 98, in check_and_unpack_rpc_response
    assert "result" in response.keys(), f"Expected result in RPC response: {json.dumps(response, indent=2)}"
AssertionError: Expected result in RPC response: {
  "jsonrpc": "2.0",
  "id": "1",
  "error": {
    "code": -32000,
    "message": "out of gas"
  }
}
SKIPPED [1] /home/sp/harmony/harmony-test/localnet/rpc_tests/test_transaction.py:250: Test cross shard transaction (hash 0x0988bcaecba9cc731245ee7ae9595d1202448413bc6e517b4c0c8da9abb1e479) already present on chain...
============================================================== 57 passed, 3 skipped in 98.10s (0:01:38) ===============================================================

=== FINISHED RPC TESTS ===

Passed RPC tests
~/harmony/harmony-test/localnet ~/harmony/harmony-test/localnet
~/harmony/harmony-test/localnet
(pythonenv) [sp@ip-172-31-10-45 localnet]$ git push origin
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 421 bytes | 421.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To github.com:harmony-one/harmony-test.git
   173af41..6582d77  master -> master
````

**Review by gupadhyaya — APPROVED** [review]

**Pull request merged**
