### PR TITLE
Mainnet Release Candidate 2023.1.2

### PR DESCRIPTION
**Pull request by ONECasey**
#4388 
#4389
#4289 
#4289

### CODE REVIEW

**Review by GheisMohammadi — APPROVED** [review]

**Review by MaxMustermann2 — APPROVED** [review]

**Comment by sophoah** [comment]
travis ci is now working after restart

**Comment by ONECasey** [comment]
Looks like some conflicts are not allowing a merge to main. Will review it today.

**Comment by ONECasey** [comment]
@Frozen Can you attempt to fix these conflicts?

**Comment by Frozen** [comment]
https://github.com/harmony-one/harmony/pull/4382
Problem somewhere in the last commit, if revert works fine.

**Pull request merged**
