### PR TITLE
Replace all logs in core module to use zerolog

### PR DESCRIPTION
**Pull request by hsienchiaolee**
## Issue

#1171 

## Test
N/A, ran `./test/test_before_submit.sh`

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by mikedoan** [comment]
Jenkins, test this please.

**Comment by mikedoan** [comment]
Jenkins, test this please.

**Comment by mikedoan** [comment]
Jenkins, test this please.

**Pull request merged**
