### PR TITLE
Wallet config file

### PR DESCRIPTION
**Pull request by LeoHChen**
* add a function in internal/utils to support read .ini format of configuration file
* define the format of the .ini file for wallet
* use -p profile in wallet to read different section of wallet configuration

### CODE REVIEW

**Comment by LeoHChen** [comment]
Example of the wallet.ini.  Tested on testnet and devnet and it works. Devnet has different issue with wallet, but it is not due to this PR.

```
$ cat .hmy/wallet.ini
[default]
bootnode = /ip4/100.26.90.187/tcp/9876/p2p/QmZJJx6AdaoEkGLrYG4JeLCKeCKDjnFz2wfHNHxAqFSGA9
bootnode = /ip4/54.213.43.194/tcp/9876/p2p/QmQayinFSgMMw5cSpDUiD9pQ2WeP6WNmGxpZ6ou3mdVFJX
shards = 1

[default.shard0.rpc]
rpc = 52.10.159.253:14555
rpc = 18.234.200.120:14555
rpc = 54.201.219.44:14555
rpc = 34.201.56.0:14555
rpc = 35.167.78.55:14555

[devnet]
bootnode = /ip4/100.26.90.187/tcp/9871/p2p/Qmdfjtk6hPoyrH1zVD9PEH4zfWLo38dP2mDvvKXfh3tnEv
bootnode = /ip4/54.213.43.194/tcp/9871/p2p/QmRVbTpEYup8dSaURZfF6ByrMTSKa4UyUzJhSjahFzRqNj
shards = 3

[devnet.shard0.rpc]
rpc = 13.57.196.136:14555
rpc = 35.175.103.144:14555
rpc = 54.245.176.36:14555

[devnet.shard1.rpc]
rpc = 35.163.188.234:14555
rpc = 54.215.251.123:14555
rpc = 54.153.11.146:14555

[devnet.shard2.rpc]
rpc = 52.201.246.212:14555
rpc = 3.81.26.139:14555
rpc = 18.237.42.209:14555

```

**Comment by alajko** [comment]
Is default profile for running wallet locally?

**Comment by LeoHChen** [comment]
> Is default profile for running wallet locally?

I haven't checked in any ini file.  I think the default profile should be for testnet.  We can definitely add a section for local test.

**Comment by alajko** [comment]
> I haven't checked in any ini file. I think the default profile should be for testnet. We can definitely add a section for local test.

It might be helpful to add a local .ini file.

**Comment by LeoHChen** [comment]
> > I haven't checked in any ini file. I think the default profile should be for testnet. We can definitely add a section for local test.
> 
> It might be helpful to add a local .ini file.

sure. I'll add one

**Pull request merged**
