### PR TITLE
Disable stream sync in localnet

### PR DESCRIPTION
**Pull request by Frozen**
Disables stream sync for `make debug`

### CODE REVIEW

**Comment by sophoah** [comment]
hey @Frozen could you explain  the reason for the PR ? what are you testing, and if a test do we need that change to be "permanent" ? Our direction is to use streamsync and disabling it doesn't make sense.

**Comment by Frozen** [comment]
Because it has https://github.com/harmony-one/harmony/issues/4749, it unstable until it will not be fixed.

**Comment by sophoah** [comment]
Considering :
1) the issue happens in localnet
2) streamsync is still experimental

I am ok with the change. However, let's have another Makefile target or an ENV so we can easily switch to and back that @mur-me can create with another PR

**Review by sophoah — APPROVED** [review]

**Comment by sophoah** [comment]
@GheisMohammadi for your information and approval, see my rational above.

**Comment by GheisMohammadi** [comment]
I don’t think this will be helpful in resolving any issue. The localnet is producing new blocks and functioning well, even with unstable connections. The proof is that all tests in the CI/CD pipeline, including the ones you've implemented, have passed. If you suspect connection issues and need to test something, I recommend trying these changes on your local system instead of submitting a PR. However, if you really need to create a PR, you could add a new command to the Makefile.

**Comment by sophoah** [comment]
closing this one since is is done in #4761

**Pull request closed without merging**
