### PR TITLE
Concurrent rpc balances queries

### PR DESCRIPTION
**Pull request by flicker-harmony**
## Issue

https://github.com/harmony-one/harmony/issues/1198

## Test execution improvement (not much, by 10-20% for mainnet)

[balancesOldTime.txt](https://github.com/harmony-one/harmony/files/3404336/balancesOldTime.txt)
[balancesNewTime.txt](https://github.com/harmony-one/harmony/files/3404337/balancesNewTime.txt)

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by LeoHChen** [comment]
I am looking for a test run benchmark of the wallet before and after this PR.  Please show the execution log of wallet balances command, and compare the execution.  Thanks.

**Comment by LeoHChen** [comment]
How is your benchmark test of the wallet?

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Pull request merged**
