### PR TITLE
Change mystatus scripts

### PR DESCRIPTION
**Pull request by kozaklukas**
Optimized the script, ready for new features to be added

Signed-off-by: Lukas Kozak <luks.kozak@gmail.com>

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by kozaklukas** [comment]
I'll soon add a feature to check FN addresses against https://raw.githubusercontent.com/harmony-one/harmony/master/internal/genesis/foundational.go and provide test logs. Then it should be g2g.

**Comment by kozaklukas** [comment]
$ ./mystatus.sh -h
Usage: ./mystatus.sh [option] command

Option:
    -h      print this help

Actions:
    1. health       - Generates a status report of your node
    2. address      - Checks if your wallet is registered in the FN list
    3. all          - Does all above

$ ./mystatus.sh all

====== ADDRESS ======

SUCCESS: one1dsgmswzkspx3at5gywltd97sj45lapaqmk0hzw FOUND in our foundational list!

====== HEALTH ======

Harmony (C) 2018. harmony, version v3538-drum_20190616b-6-g9abbf4f8 (jenkins@ 2019-06-16T07:33:25+0000)
Current Length of Chain: 3726
Your Sync Status: 3726
Your Shard: 2
Your IP: 54.235.43.76
Total Blocks Received After Syncing: 11
Using default profile for wallet
Account 0:
    Address: one1cquuj3jdrrug5f3vfe60e9pr6us74ze2vc4adw
    Balance in Shard 0:  0.0000, nonce: 0 
    Balance in Shard 1:  0.0000, nonce: 0 
    Balance in Shard 2:  0.0000, nonce: 0 
    Balance in Shard 3:  0.0000, nonce: 0

**Comment by kozaklukas** [comment]
$ ./mystatus.sh -h
Usage: ./mystatus.sh [option] command

Option:
-h print this help

Actions:
1. health - Generates a status report of your node
2. address - Checks if your wallet is registered in the FN list
3. all - Does all above

$ ./mystatus.sh all

====== ADDRESS ======

SUCCESS: one1dsgmswzkspx3at5gywltd97sj45lapaqmk0hzw FOUND in our foundational list!

====== HEALTH ======

Harmony (C) 2018. harmony, version v3538-drum_20190616b-6-g9abbf4f8 (jenkins@ 2019-06-16T07:33:25+0000)
Current Length of Chain: 3726
Your Sync Status: 3726
Your Shard: 2
Your IP: 54.235.43.76
Total Blocks Received After Syncing: 11
Using default profile for wallet
Account 0:
Address: one1dsgmswzkspx3at5gywltd97sj45lapaqmk0hzw
Balance in Shard 0: 0.0000, nonce: 0
Balance in Shard 1: 0.0000, nonce: 0
Balance in Shard 2: 0.0000, nonce: 0
Balance in Shard 3: 0.0000, nonce: 0

**Comment by kozaklukas** [comment]
Output logs, there seems to be no easy way to get the real blockchain height and node's blockchain height at the moment from the log itself, currently it reports the last OutOfSync situation (frequent bug is OutOfSync at the same myHeight and otherHeight).

We need RPC call to get the blockchain height of the node and a way to get the real blockchain height.

$ ./mystatus.sh -h
Usage: ./mystatus.sh [option] command

Option:
-h print this help

Actions:

    health - Generates a status report of your node
    address - Checks if your wallet is registered in the FN list
    all - Does all above

$ ./mystatus.sh all

====== ADDRESS ======

SUCCESS: one1dsgmswzkspx3at5gywltd97sj45lapaqmk0hzw FOUND in our foundational list!

====== HEALTH ======

Harmony (C) 2018. harmony, version v3538-drum_20190616b-6-g9abbf4f8 (jenkins@ 2019-06-16T07:33:25+0000)
Current Length of Chain: 3726
Your Sync Status: 3726
Your Shard: 2
Your IP: 54.235.43.76
Total Blocks Received After Syncing: 11
Using default profile for wallet
Account 0:
Address: one1dsgmswzkspx3at5gywltd97sj45lapaqmk0hzw
Balance in Shard 0: 0.0000, nonce: 0
Balance in Shard 1: 0.0000, nonce: 0
Balance in Shard 2: 0.0000, nonce: 0
Balance in Shard 3: 0.0000, nonce: 0

**Comment by kozaklukas** [comment]
Output logs, there seems to be no easy way to get the real blockchain height and node's blockchain height at the moment from the log itself, currently it reports the last OutOfSync situation (frequent bug is OutOfSync at the same myHeight and otherHeight).

We should have an RPC call to get the blockchain height of the node and another way to get the real blockchain height.

`$ ./mystatus.sh -h`
Usage: $0 [option] command
Option:
    -h      print this help
Actions:
    1. health       - Generates a status report of your node
    2. address      - Checks if your wallet is registered in the FN list
    3. all          - Does all above

`$ ./mystatus.sh all`

====== ADDRESS ======

SUCCESS: one1dsgmswzkspx3at5gywltd97sj45lapaqmk0hzw FOUND in our foundational list!

====== HEALTH ======

Harmony (C) 2018. harmony, version v3538-drum_20190616b-6-g9abbf4f8 (jenkins@ 2019-06-16T07:33:25+0000)
Current Length of Chain: 3726
Your Sync Status: 3726
Your Shard: 2
Your IP: 54.235.43.76
Total Blocks Received After Syncing: 11
Using default profile for wallet
Account 0:
Address: one1dsgmswzkspx3at5gywltd97sj45lapaqmk0hzw
Balance in Shard 0: 0.0000, nonce: 0
Balance in Shard 1: 0.0000, nonce: 0
Balance in Shard 2: 0.0000, nonce: 0
Balance in Shard 3: 0.0000, nonce: 0

**Pull request merged**
