### PR TITLE
[WIP][Testing] Add PR testing to Travis using Docker

### PR DESCRIPTION
**Pull request by Daniel-VDM**
## Issue

This PR will introduce an easy way for one to test their code before submitting a PR as it uses docker images. After this PR, we can remove the Jenkins requirement and hopefully reduce the time it takes to check PRs.

Note that the associated tests can be found [here](https://github.com/harmony-one/harmony-ops/tree/test-pr/test-automation/api-tests) and [here](https://github.com/SebastianJ/harmony-tests).

### CODE REVIEW

**Comment by Daniel-VDM** [comment]
Checkpoint for @ivorytowerdds

**Comment by fxfactorial** [comment]
@Daniel-VDM do we still need this open ?

**Comment by stephen-tse** [comment]
let's merge or close pr after 10 days? cc @LeoHChen

**Comment by fxfactorial** [comment]
spoke offline, fine to close for now

**Pull request closed without merging**
