### PR TITLE
Get validator info by block

### PR DESCRIPTION
**Pull request by gupadhyaya**
Added new rpc to get the validator information by block number. The existing one works as is, the new rpc GetValidatorInformationByBlockNumber requires address and hex block number as input.

### CODE REVIEW

**Comment by LeoHChen** [comment]
This PR may break staking dashboard as the RPC API is changed. Please get Minh's approval. @mikedoan

**Comment by gupadhyaya** [comment]
```
./hmy blockchain validator information-by-block-number one1pdv9lrdwl0rg5vglh4xtyrv3wjk3wsqket7zxy 0x52
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "current-epoch-performance": null,
    "currently-in-committee": false,
    "epos-status": "eligible to be elected next epoch",
    "lifetime": {
      "apr": "0.000000000000000000",
      "blocks": {
        "signed": 0,
        "to-sign": 0
      },
      "reward-accumulated": 0
    },
    "metrics": null,
    "total-delegation": 5e+22,
    "validator": {
      "address": "one1pdv9lrdwl0rg5vglh4xtyrv3wjk3wsqket7zxy",
      "bls-public-keys": [
        "65f55eb3052f9e9f632b2923be594ba77c55543f5c58ee1454b9cfd658d25e06373b0f7d42a19c84768139ea294f6204"
      ],
      "creation-height": 79,
      "delegations": [
        {
          "amount": 5e+22,
          "delegator-address": "one1pdv9lrdwl0rg5vglh4xtyrv3wjk3wsqket7zxy",
          "reward": 0,
          "undelegations": []
        }
      ],
      "details": "Ganesh the validator",
      "identity": "ganesh",
      "last-epoch-in-committee": 0,
      "max-change-rate": "0.050000000000000000",
      "max-rate": "0.500000000000000000",
      "max-total-delegation": 1e+23,
      "min-self-delegation": 2e+22,
      "name": "Ganesh",
      "rate": "0.100000000000000000",
      "security-contact": "Alex",
      "update-height": 79,
      "website": "ganesh@harmony.one"
    }
  }
}
```
```
./hmy blockchain validator all-information-by-block-number 0 0x52
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": [
    {
      "current-epoch-performance": null,
      "currently-in-committee": false,
      "epos-status": "eligible to be elected next epoch",
      "lifetime": {
        "apr": "0.000000000000000000",
        "blocks": {
          "signed": 0,
          "to-sign": 0
        },
        "reward-accumulated": 0
      },
      "metrics": null,
      "total-delegation": 5e+22,
      "validator": {
        "address": "one1pdv9lrdwl0rg5vglh4xtyrv3wjk3wsqket7zxy",
        "bls-public-keys": [
          "65f55eb3052f9e9f632b2923be594ba77c55543f5c58ee1454b9cfd658d25e06373b0f7d42a19c84768139ea294f6204"
        ],
        "creation-height": 79,
        "delegations": [
          {
            "amount": 5e+22,
            "delegator-address": "one1pdv9lrdwl0rg5vglh4xtyrv3wjk3wsqket7zxy",
            "reward": 0,
            "undelegations": []
          }
        ],
        "details": "Ganesh the validator",
        "identity": "ganesh",
        "last-epoch-in-committee": 0,
        "max-change-rate": "0.050000000000000000",
        "max-rate": "0.500000000000000000",
        "max-total-delegation": 1e+23,
        "min-self-delegation": 2e+22,
        "name": "Ganesh",
        "rate": "0.100000000000000000",
        "security-contact": "Alex",
        "update-height": 79,
        "website": "ganesh@harmony.one"
      }
    }
  ]
}
```

**Comment by stephen-tse** [comment]
well done on adding to our v1 api doc, but not in v2 api doc?

https://api.os.hmny.io/?version=latest#a5c5da83-fa0b-46c6-8e5f-c8eec613fefd
https://api.os.hmny.io/?version=latest#79d79ea3-f400-4a21-9153-974e258a4fd0

**Comment by stephen-tse** [comment]
@LeoHChen did we push out a new cli binary version yet? if not, who should own the process?

`
$ curl -LO https://harmony.one/hmycli && mv hmycli hmy && chmod +x hmy
$ ./hmy version
Harmony (C) 2020. hmy, version v333-80a4f42 (root@harmony.one 2020-03-21T19:26:19+0000)

$ ./hmy blockchain validator all-information-by-block-number

Look up information about validator information

Usage:
  hmy blockchain validator [flags]
  hmy blockchain validator [command]

Available Commands:
  all             all validator addresses
  all-information all validators information
  elected         elected validators
  information     original creation record of a validator
  metrics         metrics about the performance of a validator
`

**Pull request merged**
