### PR TITLE
Create 1+3 sharded genesis setup 

### PR DESCRIPTION
**Pull request by rlan35**
Before our network only support one shard of beacon chain and our genesis sharding state only have beacon chain populated. Now we have sharded p2p network and also 1+3 gensis shards.

Tested locally with 5 node each shard and 10 node each shard.

### CODE REVIEW

**Comment by LeoHChen** [comment]
I'll have to modify the aws deploy script in order to test this PR.  Will do it tonight and post the test results here.

**Comment by LeoHChen** [comment]
4 shards, 1278 consensus, 2172 total TPS, 38 nodes
54.235.230.87, 315, 550.436
34.205.77.113, 318, 564.09
52.87.250.168, 327, 491.102
34.201.127.138, 318, 566.503
all logs are uploaded to
s3://harmony-benchmark/logs/20190328.064554

**Comment by rlan35** [comment]
> tested it in AWS. it works!!
> 
> Please set each shard to 50 nodes.

Done.

**Comment by LeoHChen** [comment]
Jenkins, test it please.

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by rlan35** [comment]
> Jenkins, test this please.

Seems Jenkins still failing. What's the reason?

**Comment by LeoHChen** [comment]
> > Jenkins, test this please.
> 
> Seems Jenkins still failing. What's the reason?

let me check the server.

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Pull request merged**
