### PR TITLE
[Rosetta] Track internal transactions 

### LINKED ISSUE #3434: [Rosetta] Track 'internal' contract transfer balances
## Issue

Currently, any 'internal' transfers of native ONE tokens (from a contract to a receiver) cannot be tracked with our rosetta implementation. An example of such a balance that cannot be tacked is our [funding smart contract](https://github.com/harmony-one/HRC/blob/751b856c8b205c3d1ff4815dc5a7d1f02236a2e4/examples/node-faucet/contracts/Faucet.sol#L24-L31) used earlier this year.

## Proposed solution

We could use a contract trace that would be introduced with this PR: #3389.  From some research below, it looks like we only need to check for the `CALL` & `CALLCODE` opcode and report the balance change.

Explicitly, we can just trace and check for 'internal' transfers if we see that the transaction has some data in the data field. 

### Stack exchange post
[Stack exchange post about `CALL` args](https://ethereum.stackexchange.com/questions/16832/internal-message-call-call-opcode)

### Instruction deep dive
Here are the calls that transfer a balance from the contract to another account.

**`CALL` Opcode execution:**

https://github.com/harmony-one/harmony/blob/e165c4d55c5bd9897c233b6770a70d183ba5ee70/core/vm/instructions.go#L749-L763 

**A transfer resulting from `CALL` opcode execution:**

https://github.com/harmony-one/harmony/blob/e165c4d55c5bd9897c233b6770a70d183ba5ee70/core/vm/evm.go#L199-L238 

**`CALLCODE` Opcode execution:**

https://github.com/harmony-one/harmony/blob/e165c4d55c5bd9897c233b6770a70d183ba5ee70/core/vm/instructions.go#L778-L792

**A transfer resulting from `CALLCODE` opcode execution:**

https://github.com/harmony-one/harmony/blob/e165c4d55c5bd9897c233b6770a70d183ba5ee70/core/vm/evm.go#L285-L309

(Main contract interpreter loop)
https://github.com/harmony-one/harmony/blob/e165c4d55c5bd9897c233b6770a70d183ba5ee70/core/vm/evm.go#L48-L71

### PR DESCRIPTION
**Pull request by Daniel-VDM**
This PR closes #3434

## Additional Changes

In order to expose internal transactions, some extra field was added to the trace's `ExecutionResult`. Namely, I added the contract address (to account for nested method calls across different contracts) and opcode caller (for future use and to account for nest method calls across different contracts). 

Note that I correct the output of the trace RPC, this will break any implementation that already consumes this RPC. However, this is necessary for consistency and fixes an oversight during the review process of the initial trace PR. 

Some major refactoring of the operation formatter was done at the same time to make things more consistent. 

## Testing

I've tested this implementation locally using [this payable contract](https://github.com/harmony-one/HRC/blob/751b856c8b205c3d1ff4815dc5a7d1f02236a2e4/examples/node-faucet/contracts/Faucet.sol). 

The output of `/block/transaction` looks something like this:
```json
{
    "transaction": {
        "transaction_identifier": {
            "hash": "0xd2d60e355605cc4ea69e6fda748bda60beef9b2bc9699064311582358f96a91e"
        },
        "operations": [
            {
                "operation_identifier": {
                    "index": 0
                },
                "type": "Gas",
                "status": "success",
                "account": {
                    "address": "one19fz0vz0cvr20lzp4l8kpmxc6ekhplkwtqn9m2v",
                    "metadata": {
                        "hex_address": "0x2a44F609F860D4FF8835F9EC1d9b1AcDAE1FD9cb"
                    }
                },
                "amount": {
                    "value": "-76956000000000",
                    "currency": {
                        "symbol": "ONE",
                        "decimals": 18
                    }
                }
            },
            {
                "operation_identifier": {
                    "index": 1
                },
                "type": "NativeTransfer",
                "status": "success",
                "account": {
                    "address": "one19fz0vz0cvr20lzp4l8kpmxc6ekhplkwtqn9m2v",
                    "metadata": {
                        "hex_address": "0x2a44F609F860D4FF8835F9EC1d9b1AcDAE1FD9cb"
                    }
                },
                "amount": {
                    "value": "0",
                    "currency": {
                        "symbol": "ONE",
                        "decimals": 18
                    }
                }
            },
            {
                "operation_identifier": {
                    "index": 2
                },
                "related_operations": [
                    {
                        "index": 1
                    }
                ],
                "type": "NativeTransfer",
                "status": "success",
                "account": {
                    "address": "one1f38aa9mlh0nj9nwl2uva0mw53pgshct2q20lss",
                    "metadata": {
                        "hex_address": "0x4C4FdE977FBbE722cdDf5719D7EDD488510bE16a"
                    }
                },
                "amount": {
                    "value": "0",
                    "currency": {
                        "symbol": "ONE",
                        "decimals": 18
                    }
                }
            },
            {
                "operation_identifier": {
                    "index": 3
                },
                "type": "NativeTransfer",
                "status": "success",
                "account": {
                    "address": "one1f38aa9mlh0nj9nwl2uva0mw53pgshct2q20lss",
                    "metadata": {
                        "hex_address": "0x4C4FdE977FBbE722cdDf5719D7EDD488510bE16a"
                    }
                },
                "amount": {
                    "value": "-10000000000000000000000",
                    "currency": {
                        "symbol": "ONE",
                        "decimals": 18
                    }
                }
            },
            {
                "operation_identifier": {
                    "index": 4
                },
                "related_operations": [
                    {
                        "index": 3
                    }
                ],
                "type": "NativeTransfer",
                "status": "success",
                "account": {
                    "address": "one13lu674f3jkfk2qhsngfc2vhcf372wprctdjvgu",
                    "metadata": {
                        "hex_address": "0x8fF9aF553195936502f09A138532f84c7CA70478"
                    }
                },
                "amount": {
                    "value": "10000000000000000000000",
                    "currency": {
                        "symbol": "ONE",
                        "decimals": 18
                    }
                }
            }
        ],
        "metadata": {
            "contract_account_identifier": {
                "address": "one1f38aa9mlh0nj9nwl2uva0mw53pgshct2q20lss",
                "metadata": {
                    "hex_address": "0x4C4FdE977FBbE722cdDf5719D7EDD488510bE16a"
                }
            },
            "data": "230244080000000000000000000000008ff9af553195936502f09a138532f84c7ca70478"
        }
    }
}
```

## Documentation

Some changes to the related operations were done for all transactions that consume gas. The example and description in the docs need to be updated for [api.hmny.io](https://api.hmny.io/). Postman PR to the working branch is [here](https://harmony.postman.co/workspace/My-Workspace~04f8dad4-94f8-49a8-8b7f-8e7738f41628/pull-request/05c09ca2-571c-4f58-8499-b61ee501909f?workspace=04f8dad4-94f8-49a8-8b7f-8e7738f41628) (perms needed).

### CODE REVIEW

**Review by LeoHChen — APPROVED** [review]
Do you need to include any test of this case in travis? 
Otherwise, it looks okay to me in general, but I don't know much of the evm internal.  Better get @rlan35 's approval on this PR as well.

**Comment by Daniel-VDM** [comment]
> Do you need to include any test of this case in travis?
> Otherwise, it looks okay to me in general, but I don't know much of the evm internal. Better get @rlan35 's approval on this PR as well.

I think the unit test should be sufficient as it relies on the evm trace to get the internal transaction, which is mocked on the unit test. Of course, more tests using a localnet would be nice to ensure the trace works for all sorts of contracts that does an internal tx. However, coding up these tests is not a simple task and is ultimately part of a bigger “trace integration test” that should be written in the future. Moreover, the trace logic was taken from geth, which for the most part indicates that it’s solid. Therefore, I don’t see a huge benefit to code up a test using localnet for this specific PR.

**Review by rlan35 — APPROVED** [review]

**Comment by rlan35** [comment]
I believe this PR won't affect onchain evm's running, but just want to confirm with you.

**Comment by Daniel-VDM** [comment]
> I believe this PR won't affect onchain evm's running, but just want to confirm with you.

Yep, nothing with the EVM is changed. Only the trace (which is a *replay* of a finalized block & transaction) exposes 2 additional fields: contract address and caller address.

**Pull request merged**
