### PR TITLE
[node.sh] uses separate options to download harmony db

### PR DESCRIPTION
**Pull request by LeoHChen**
Signed-off-by: Leo Chen <leo@harmony.one>

### CODE REVIEW

**Comment by nyetwurk** [comment]
https is the worst possible way to download a large file, No way to do it incrementally. Rsync would make much much more sense.

**Comment by nyetwurk** [comment]
also, recommend at least .gz so there is a bit of a wrapper around the tar file. Sums are a good backup, but bare tar files (especially large ones) are not suitable for passing around.

**Comment by fxfactorial** [comment]
@nyetwurk `http` spec has multi-part upload, not sure if curl is smart enough to use that

**Comment by nyetwurk** [comment]
@fxfactorial Either way, you're best off using rsync with untarred multiple files so it can incrementally download them. Also, if the snapshot gets updated, you can rsync from a newer snapshot and rsync will only download the changed files. That can't be done with http.

**Comment by fxfactorial** [comment]
@nyetwurk I understand your PoV (and am well aware of the benefits of rsync) but assuming rsync exists on user machine is another assumption, plus assuming same behavior between all the possible versions/impl of rsync.

**Pull request merged**
