### PR TITLE
Concurrent rpc balances queries

### PR DESCRIPTION
**Pull request by flicker-harmony**
Concurrent rpc requests for balances in each shard for better performance.

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by LeoHChen** [comment]
@flicker-harmony , please follow https://github.com/harmony-one/harmony-open/tree/master/git-cheat-sheet,  don't submit a branch to the main repo.  You need to fork it at first.

**Comment by LeoHChen** [comment]
Please also append a test log in gist.

**Comment by flicker-harmony** [comment]
Will do

**Pull request closed without merging**
