### PR TITLE
Fix missing IP/port from logs

### PR DESCRIPTION
**Pull request by hsienchiaolee**
## Issue

#1173 caused IP/Port to be missing from log context.

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by hsienchiaolee** [comment]
Jenkins, test this please.

**Comment by chaosma** [comment]
Jenkins test this please

**Pull request merged**
