### PR TITLE
[test/txgen] Remove txgen #1635

### PR DESCRIPTION
**Pull request by Daniel-VDM**
Removed the test txgen as it does not work anymore.

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by LeoHChen** [comment]
There is a few places, like in our build script, and test scripts referring to txgen.  You need to find all the occurrence of txgen and remove them, including https://github.com/harmony-one/experiment-deploy

**Comment by LeoHChen** [comment]
And https://github.com/harmony-one/jenkins

**Comment by Daniel-VDM** [comment]
Okay, I will do a full clean once the benchmarking tool is done.

**Pull request closed without merging**
