### PR TITLE
Increase test coverage by 10% or more

### PR DESCRIPTION
**Pull request by animesh371**
## Issue

https://github.com/harmony-one/harmony/issues/316

## Test
Added tests for Identity messages

#### Test Coverage Data

* Before
?   	github.com/harmony-one/harmony/api/proto/identity	[no test files]
* After
PASS
coverage: 86.7% of statements
ok  	github.com/harmony-one/harmony/api/proto/identity	0.009s

### CODE REVIEW

**Comment by LeoHChen** [comment]
Can one of the admins verify this patch?

**Comment by alajko** [comment]
Hi @animesh371 , Thanks a lot for your effort. We would be getting rid of identity message type but we can repurpose the logic of your code for the new message type. Stay tuned. (cc: @LeoHChen, @mikedoan).

**Comment by LeoHChen** [comment]
@animesh371 , please fill out the test coverage data for this PR. Just goto the directory and run "go test -cover"

**Comment by animesh371** [comment]
Thanks @rlan35 , you can merge my PR. I'll identify and add more test cases.

**Comment by mikedoan** [comment]
@animesh371 we can not merge it due to conflicts.

**Comment by animesh371** [comment]
@mikedoan , I have rebased changes from master. Could you check now.

**Pull request merged**
