### PR TITLE
[CMD] Command overhaul

### PR DESCRIPTION
**Pull request by JackyWYX**
## 1. Description

This is another PR for issue [#3110]. This PR overhauls the command line interface.

1. Commands are rewritten with cobra.
2. All flags (new flags and legacy flags) are parsed into `harmonyConfig`.
3. The `harmonyConfig` can be dumped to a file with `dumpconfig` command.
4. The config file can be loaded with `--config` flag. Loaded config can override with custom flags.
5. Functionality of all existing flags are preserved in this PR (all in legacy flags) and legacy logic are not changed either. 

### Claim 1. Break change in command line interface

1. All flags should be specified with double dash instead of single dash.
2. Staking mode is on by default. If want to run in legacy mode, use `--staking=false` or `--run.legacy`
3. Though all legacy fields become hidden for `-h`, all these functionality are supported.

### Claim 2. Not compatible with previous node.sh

Because of the fact in claim 1, this PR is NOT compatible with previous node.sh.

On the other side, node.sh command is still compatible.

### Claim 3. This PR is NOT ready to release

Reasons:
1. Some legacy code need to check with Leo and RJ for whether we should continue supporting these flags - Dealing with legacy is expensive. We shall make this command line interface a clean start.
2. Some legacy flags (IP and port) are separated to different flags (rpc.ip/port, ws.ip/port, p2p.ip/port) in this PR. However these flags are just defined but not used so far.

### Claim 4. This PR is big

1. This PR contains unmerged code in https://github.com/harmony-one/harmony/pull/3219. (~2000 lines)
2. There is a natural dilemma between make it work and make it small. In order to make it work, this size is the best I can do.

### Claim 5. Foundation node supports

This PR shall not be released. We shall only release once after the mega project removing node.sh is totally done (to minimize the impact of the foundation nodes).

### 2.1 Change the ip/port usage. 

Do all port maths (+500, -3000...) at command line instead of confusing user with a single 9000 port but actually taking 4 ports (6000, 9000, 9500, 9800). Also user can choose whether to open these RPC calls separately by specifying the IP address to listen.  Currently these ports are just defined but not used.

Also, we can preserve the legacy --port or --ip field for simplicity. (Done in https://github.com/harmony-one/harmony/pull/3261)

### 2.2 Determine whether we can hard code and remove these flags:

1. bls.maxkeys
2. consensus.delay-commit
3. consensus.block-time
4. consensus.min-peers
5. txpool.broadcast-invalid-tx

(Done in https://github.com/harmony-one/harmony/pull/3274)

### 2.3 Check whether we can remove log context

Currently, each log message has ip and ctx field recorded, which takes a lot of space and does not have that much use (IP and port shall be collected as metadata in log service). Another usage of the log ip/port is defining the file name of the log. So can we mark these fields as deprecated in the future? (log context and file name is still available when start node with `--port` `--ip` flags in this PR)

(Done already in this PR)

### 2.4 naming for flag `--run.legacy`

Is legacy mode (equals to `--staking=false` in previous version) only run for internal nodes? Does it makes more sense if we rename the flag to `--run.internal`?

### 2.5 Move more node.sh setting logic into binary

* systemctl env settings
* static linked library

(As discussed in https://github.com/harmony-one/harmony/issues/3257, it would better not to import these env settings.)
 
#### Public flags:

```
      --bls.dir string             directory for BLS keys (default "./.hmy/blskeys")
      --bls.keys strings           a list of BLS key files (separated by ,)
      --bls.kms                    enable BLS key decryption with AWS KMS service (default true)
      --bls.kms.config string      json config file for KMS service (region and credentials)
      --bls.kms.src string         the AWS config source (region and credentials) for KMS service (shared, prompt, file) (default "shared")
      --bls.pass                   enable BLS key decryption with passphrase (default true)
      --bls.pass.file string       the pass file used for BLS decryption. If specified, this pass file will be used for all BLS keys
      --bls.pass.save              after input the BLS passphrase from console, whether to persist the input passphrases in .pass file
      --bls.pass.src string        source for BLS passphrase (auto, file, prompt) (default "auto")
      --bootnodes strings          a list of bootnode multiaddress (delimited by ,)
  -c, --config string              load node config from the config toml file.
      --datadir string             directory of chain database (default "./")
      --devnet.hmy-node-size int   number of Harmony-operated nodes per shard for devnet (negative means equal to --devnet.shard-size) (default 10)
      --devnet.num-shard int       number of shards for devnet (default 2)
      --devnet.shard-size int      number of nodes per shard for devnet (default 10)
      --dns.port int               port of customized dns node (default 9000)
      --dns.zone string            use customized peers from the zone for state syncing
  -h, --help                       help for harmony
      --http                       enable HTTP / RPC requests (default true)
      --http.ip string             ip address to listen for RPC calls (default "127.0.0.1")
      --http.port int              rpc port to listen for RPC calls (default 9000)
      --log.dir string             directory path to put rotation logs (default "./latest")
      --log.max-size int           rotation log size in megabytes (default 100)
      --log.name string            log file name (e.g. harmony.log) (default "harmony.log")
  -v, --log.verb int               logging verbosity: 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=detail (default 3)
  -n, --network string             network to join (mainnet, testnet, pangaea, localnet, partner, stressnet, devnet) (default "mainnet")
      --p2p.ip string              ip to listen for p2p protocols (default "127.0.0.1")
      --p2p.keyfile string         the p2p key file of the harmony node (default "./.hmykey")
      --p2p.port int               port to listen for p2p protocols (default 9000)
      --pprof                      enable pprof profiling
      --pprof.addr string          listen address for pprof (default "127.0.0.1:6060")
      --run string                 run node type (validator, explorer) (default "validator")
      --run.archive                run node in archive mode
      --run.legacy                 whether to run node in legacy mode
      --run.shard int              run node on the given shard ID (-1 automatically configured by BLS keys) (default -1)
      --txpool.blacklist string    file of blacklisted wallet addresses (default "./.hmy/blacklist.txt")
      --ws                         enable websocket endpoint (default true)
      --ws.ip string               ip endpoint for websocket (default "127.0.0.1")
      --ws.port int                port for websocket endpoint (default 9000)
```

### 2. dump config content

```
Version = "1.0.0"

[BLSKeys]
  KMSConfigFile = ""
  KMSConfigSrcType = "shared"
  KMSEnabled = true
  KeyDir = "./.hmy/blskeys"
  KeyFiles = []
  MaxKeys = 10
  PassEnabled = true
  PassFile = ""
  PassSrcType = "auto"
  SavePassphrase = false

[Consensus]
  BlockTime = "8s"
  DelayCommit = "0ms"
  MinPeers = 32

[General]
  DataDir = "./"
  IsArchival = false
  NoStaking = false
  NodeType = "validator"
  ShardID = -1

[Log]
  FileName = "harmony.log"
  Folder = "./latest"
  RotateSize = 100
  Verbosity = 3

[Network]
  BootNodes = ["/ip4/100.26.90.187/tcp/9874/p2p/Qmdfjtk6hPoyrH1zVD9PEH4zfWLo38dP2mDvvKXfh3tnEv","/ip4/54.213.43.194/tcp/9874/p2p/QmZJJx6AdaoEkGLrYG4JeLCKeCKDjnFz2wfHNHxAqFSGA9","/ip4/13.113.101.219/tcp/12019/p2p/QmQayinFSgMMw5cSpDUiD9pQ2WeP6WNmGxpZ6ou3mdVFJX","/ip4/99.81.170.167/tcp/12019/p2p/QmRVbTpEYup8dSaURZfF6ByrMTSKa4UyUzJhSjahFzRqNj"]
  DNSPort = 9000
  DNSZone = "t.hmny.io"
  LegacySyncing = false
  NetworkType = "mainnet"

[P2P]
  IP = "127.0.0.1"
  KeyFile = "./.hmykey"
  Port = 9000

[Pprof]
  Enabled = false
  ListenAddr = "127.0.0.1:6060"

[RPC]
  Enabled = true
  IP = "127.0.0.1"
  Port = 9000

[TxPool]
  BlacklistFile = "./.hmy/blacklist.txt"
  BroadcastInvalidTx = false

[WS]
  Enabled = true
  IP = "127.0.0.1"
  Port = 9000
```

### CODE REVIEW

**Comment by LeoHChen** [comment]
Please rebase this PR on top of the latest main branch.

**Comment by JackyWYX** [comment]
> latest

Done. Thanks for reminder

**Comment by rlan35** [comment]
bls.maxkeys   - yes, can hard code
consensus.delay-commit   - yes, can hard code
consensus.block-time   - yes, can hard code
consensus.min-peers - prefer no
txpool.broadcast-invalid-tx - prefer no

**Comment by JackyWYX** [comment]
My original intention to build multiple PRs for command overhaul (#3253, #3261, #3274) was to incrementally add changes to the repository. However, since #3253 has not been merged for a long time, so multiple branches will only cause ambiguity. Other than that, some bugs is found so this PR is not completely self-contained. So will close this PR and reopen a new one.

**Pull request closed without merging**
