### PR TITLE
staking: enable migration precompile

### PR DESCRIPTION
**Pull request by MaxMustermann2**
This change [re-](https://github.com/harmony-one/harmony/pull/3906#issuecomment-1014158304)adds support for staking migration to the staking precompile located at `0xFC`. Staking migration is defined as the transfer of all delegated balance, undelegated balance, and pending rewards from address A to address B. In the event that a wallet's private key is compromised, a single transaction can transfer all the staked balance (+ rewards) to a new, clean address. 

We have seen a few events where attackers undelegate the balances of compromised users, and wait for the 7 epoch period to end. A user who notices this transaction on time may redelegate their balance to save it, but no other transaction is possible because the malicious attacker can steal any unlocked funds. This ends up becoming a cat and mouse game where the attacker undelegates and the owner delegates, on repeat. This change is built to work around that, by allowing users to transfer their (locked) funds to a new address.

### CODE REVIEW

**Comment by MaxMustermann2** [comment]
The migration of delegated / locked balances can be transferred by anyone (original owner or malicious attacker, whoever has access to the private key), to a new address. Unless the original owner immediately, upon compromise of the key, makes such a transaction, the attacker can create the same transaction to an address controlled by them. 

We can work around the above hole by making use of the denylist / allowlist of transactions, but that can be done without needing a migration precompile in the first place. My suggestion, therefore, is to not merge it, unless we plan to add another level of (possibly centralized) filtering to such a transaction.

**Comment by GheisMohammadi** [comment]
This is very interesting challenge. The concern is this feature is a double-edged sword. It can be used by attacker as well to drain the account as fast as possible. If a user is not aware of such a feature and attacker do some phishing attack to get him sign the transaction, account owner will lose everything. Do you think this concern is right?

**Comment by sophoah** [comment]
the same non precompile feature was suggested into our protocol at one point, we decided to not implement for the reason mentioned above.

I am also against to implement this. 7 days locked staking is also a safety feature against private key leak

**Comment by MaxMustermann2** [comment]
BREAKING CHANGES: Following the hard fork, (1) the staking precompile
will not accept any transactions with a `msg.value` attached to them;
and (2) the event topic hash of CollectRewards will change to include
the return type; and lastly, (3) the event data will be correctly padded
to 32 bytes, or `uint256`.

**Comment by ONECasey** [comment]
After careful review with the rest of the team, we agreed not to push this feature forward at this time.

**Pull request closed without merging**
