### PR TITLE
[WIP] State transition unit tests

### PR DESCRIPTION
**Pull request by gupadhyaya**
This PR adds unit tests to staking_verifier.go and state_transition.go. Not yet ready to be merged, need to refactor some.

### CODE REVIEW

**Comment by fxfactorial** [comment]
Same here , part of txn refactor , possible to close ?

**Comment by gupadhyaya** [comment]
@JackyWYX would you be able to refactor these tests as well?

**Comment by JackyWYX** [comment]
> @JackyWYX would you be able to refactor these tests as well?

Sure. Will work on this.

**Comment by gupadhyaya** [comment]
> > @JackyWYX would you be able to refactor these tests as well?
> 
> Sure. Will work on this. BTW, what is the PR for the refactoring code?

This is the only PR. Initially worked on by Wen Zhang (intern) and then I had some efforts, but it needs refactoring, as some of the tests are not so useful.

**Comment by fxfactorial** [comment]
Can we close ?

**Comment by JackyWYX** [comment]
I have taken over this issue, and I am currently working on another branch. I can open another when I finished unit test coding. So as far as I see, the PR can be closed. Still would better ask @gupadhyaya for his confirmation.

**Pull request closed without merging**
