### PR TITLE
Add 50 FN

### PR DESCRIPTION
**Pull request by charleszqwang**
-Some Key Swaps

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by lijiang2087** [comment]
okay to test :)

**Comment by xChickens** [comment]
add to whitelist

**Comment by LeoHChen** [comment]
don't do a merge when you submit a PR.  I'd prefer a rebase of existing r3
branch.

-----
Leo Chen

work hard, play hard, make history.
culture <https://harmony.one/culture>, team <https://harmony.one/team/>,
deck <https://harmony.one/deck>, roadmap <http://harmony.one/roadmap>,
vision <https://harmony.one/xoogler>, research
<https://harmony.one/research>, whitepaper <https://harmony.one/whitepaper>,
code <https://github.com/harmony-one/harmony>, annual-letter
<https://harmony.one/annual-letter>, newsletter <https://harmony.one/news>,
overview <http://harmony.one/overview>, binance-report
<https://harmony.one/binance-report>

**Pull request closed without merging**
