### PR TITLE
improve p2p host connection manager, remove quic transporters

### PR DESCRIPTION
**Pull request by GheisMohammadi**
## Issue
This PR improves p2p host connection manager and removes QUIC transporters from p2p host.

### CODE REVIEW

**Comment by Frozen** [comment]
WithSilencePeriod sets the silence period.
The connection manager will perform a cleanup once per silence period
if the number of connections surpasses the high watermark.

**Comment by Frozen** [comment]
WithGracePeriod sets the grace period.
The grace period is the time a newly opened connection is given before it becomes
subject to pruning.

**Comment by Frozen** [comment]
What is our current "high watermark"?

**Comment by Frozen** [comment]
You have to merge [this one](https://github.com/harmony-one/harmony/pull/4703) as well to pass tests.

**Comment by GheisMohammadi** [comment]
> What is our current "high watermark"?

192

**Review by sophoah — APPROVED** [review]

**Review by Frozen — APPROVED** [review]

**Review by ONECasey — APPROVED** [review]

**Pull request merged**
