### PR TITLE
Improve address and shardID validation for the wallet

### PR DESCRIPTION
**Pull request by SebastianJ**
## Issue

It's currently possible to supply invalid addresses and shard ids to the wallet binary when sending transactions.

We had multiple bug reports about this for the Pangaea bug bounty program.

I've implemented regex testing of bech32 and base16 formatted addresses so that only valid addresses according to those formats can send transactions. The previous validation check using `len(common.Address) != 20` is still included in the validation checking.

Here's a bunch of wallet invocations and their respective responses before and after this pull request:

#### Invalid addresses:

```
./bin/wallet -p local transfer --from FOOFOOFOO --to one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --amount=0.0001 --shardID=0 --toShardID=0 --pass pass:
Using local profile for wallet
Balance is not enough for the transfer, current balance is 0.000000
```

```
./bin/wallet -p local transfer --from one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --to FOOFOOFOO --amount=0.0001 --shardID=0 --toShardID=0 --pass pass:
Using local profile for wallet
Unlock account succeeded! 'pass:'
Transaction Id for shard 0: 0x9d41bd231856ab8f6a96d606a81485934db5a3134ac8a435961a6a29c168fde4
```

#### Invalid shards:

```
./bin/wallet -p local transfer --from one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --to one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --amount=0.0001 --shardID=22 --toShardID=0 --pass pass:
Using local profile for wallet
panic: runtime error: index out of range

goroutine 1 [running]:
main.processTransferCommand()
	/Users/sebastianjohnsson/Programming/Golang/src/github.com/harmony-one/harmony/cmd/client/wallet/main.go:716 +0x13bb
main.main()
	/Users/sebastianjohnsson/Programming/Golang/src/github.com/harmony-one/harmony/cmd/client/wallet/main.go:247 +0x55f
```
	
```
./bin/wallet -p local transfer --from one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --to one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --amount=0.0001 --shardID=0 --toShardID=22 --pass pass:
Using local profile for wallet
Unlock account succeeded! 'pass:'
Transaction Id for shard 0: 0x0968f0024ca453595a6e9db1692f104c8658005d4864a0734056e83234d9daae
```

#### Invalid addresses:

```
./bin/wallet -p local transfer --from FOOFOOFOO --to one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --amount=0.0001 --shardID=0 --toShardID=0 --pass pass:
Using local profile for wallet
The sender address you supplied (FOOFOOFOO) is in an invalid format. Please provide a valid address.
```

```
./bin/wallet -p local transfer --from one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --to FOOFOOFOO --amount=0.0001 --shardID=0 --toShardID=0 --pass pass:
Using local profile for wallet
The receiver address you supplied (FOOFOOFOO) is in an invalid format. Please provide a valid address.
```

#### Invalid shards:

```
./bin/wallet -p local transfer --from one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --to one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --amount=0.0001 --shardID=22 --toShardID=0 --pass pass:
Using local profile for wallet
Please specify a valid sender shard ID for the transfer (e.g. --shardID=0)
```

```
./bin/wallet -p local transfer --from one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --to one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --amount=0.0001 --shardID=0 --toShardID=22 --pass pass:
Using local profile for wallet
Please specify a valid receiver shard ID for the transfer (e.g. --toShardID=0)
```

## Test

Run the test like this:
`$ go test cmd/client/validation/*.go`

#### Test Coverage Data

`$ go test -cover
Using local profile for wallet
PASS
coverage: 100.0% of statements
ok  	github.com/harmony-one/harmony/cmd/client/validation	0.019s`

## TODO
I wasn't entirely sure where to place the code in the codebase. I just put it under cmd/client because it might only be used for validating input for the client/wallet.

Let me know if it should be moved to internal/utils or something else instead.

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by SebastianJ** [comment]
Sorry about all of the linting commits btw, the Go package for my editor (Textmate) was enforcing formatting that messed the formatting for golint / goimport.

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by SebastianJ** [comment]
Realized that I didn't add the validation to where --address can be passed as an argument, e.g. balances, getFreeToken and format.

Here's the output before implementing these new validation rules:

### Before:

#### balances:

```
./bin/wallet -p local balances --address FOOFOOFOO

Using local profile for wallet
Account: one1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq0r0azn6:
    Balance in Shard 0:  0.0000, nonce: 0 
    Balance in Shard 1:  0.0000, nonce: 0 
```

#### getFreeToken:

```
./bin/wallet -p local getFreeToken --address FOOFOOFOO

Using local profile for wallet
Transaction Id requesting free token in shard 0: 0xa81854d6e1e918453ced28df6712fafffeb2f508353963bb6e9ee97f06f22f3a
Transaction Id requesting free token in shard 1: 0x798c2640be64762dcc0f8f77579d0328fde1e93aec238ee8dd30a73be57f3bfe
```

#### format:
	
```
./bin/wallet -p local format --address FOOFOOFOO

account address in Bech32: one1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq0r0azn6
account address in Base16 (deprecated): 0x000000000000000000000000000000000000000F
```


### After:

#### balances:

```
./bin/wallet -p local balances --address FOOFOOFOO

Using local profile for wallet
The address you supplied (FOOFOOFOO) is in an invalid format. Please provide a valid address.
```

#### getFreeToken:

```
./bin/wallet -p local getFreeToken --address FOOFOOFOO

Using local profile for wallet
The address you supplied (FOOFOOFOO) is in an invalid format. Please provide a valid address.
```

#### format:
	
```
./bin/wallet -p local format --address FOOFOOFOO

The address you supplied (FOOFOOFOO) is in an invalid format. Please provide a valid address.
```

**Comment by fxfactorial** [comment]
@SebastianJ Thank you, this is good work. 

Two points:

1) Could you keep this with the wallet code rather than separate directory of `client/validation`. 
2) I would ask that more development, past this PR which I will merge once (1) satisfied, be done in the go-sdk code we have; that is, the address validation could be ported here: 

https://github.com/harmony-one/go-sdk/blob/master/cmd/subcommands/custom-flags.go

which that is/will be the official new wallet CLI

**Comment by SebastianJ** [comment]
@fxfactorial Ok, got it.

I'll move the validation code over to the wallet dir/package.

Wasn't aware of go-sdk - do you want me to port the validation over to that repo as well?

**Comment by fxfactorial** [comment]
That would be good because this is good code and would make the CLI more robust.

**Comment by SebastianJ** [comment]
Ok, moved the two validation methods to the bottom of cmd/client/wallet/main.go and the test to cmd/client/wallet/validation_test.go.

Good to go for a merge? Or do you want me to do any more changes?

**Comment by fxfactorial** [comment]
@SebastianJ No, looks good, as soon as travis clears, I will merge.

**Comment by fxfactorial** [comment]
@SebastianJ Travis failed, you can recreate the failure with `go get -v ./...` in root of project.

**Comment by SebastianJ** [comment]
Ok, I ran the command.

First time around:
```
$ go get -v ./...
github.com/harmony-one/harmony/internal/attack
github.com/harmony-one/harmony/accounts/abi/bind
github.com/harmony-one/harmony/cmd/client/wallet
github.com/harmony-one/harmony/core/vm/runtime
$
```

Second time (no output):
```
$ go get -v ./...
$ 
```

But there's nothing to push according to Git. Could it have been a temporary issue with Travis? Last runs finished without any issues.

**Comment by fxfactorial** [comment]
@SebastianJ I'll check out your branch today and run, see what is wrong.

**Comment by SebastianJ** [comment]
I refactored the validateAddress method - don't know why I initially wrote it to check for one/0x prefixes instead of just doing the validation from the get go in Regexp 🤷‍♂️

Any potential performance hit due to only using Regexp is probably negligible because the code is only invoked via CLI anyways and not reused a bunch of times across go routines etc.

Seems TravisCI also passed this time around - I think the last build just crashed somehow because it couldn't fetch packages properly.

**Comment by fxfactorial** [comment]
Great, thank you!

**Pull request merged**
