### PR TITLE
Send ints as ints, unify json logging tagging, grammar fixes

### PR DESCRIPTION
**Pull request by nyetwurk**
"BlockNum" vs "blockNum" vs "MsgBlockNum" vs "hdrBlockNum"
"BlockHash" vs "blockHash"

When trying to do monitoring, the mix of json fields is very difficult to unravel. This attempts to make naming a bit more consistent.

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by nyetwurk** [comment]
This what trying to fix this in beats looks like:
```yaml
filebeat_processors_conf:
- convert:
    fields:
    - { from: "json.lvl", to: "json.level", type: "string" } # remap old logging to zerologging tag
    - { from: "json.blockShard", type: "integer" }
    - { from: "json.blockEpoch", type: "integer" }
    - { from: "json.blockHeight", type: "integer" }
#   - { from: "json.blockNumber", type: "integer" }  # this is the bad one, index is broken
    - { from: "json.blockNumber", to: "json.blockNum", type: "integer" }  # move it to blockNum since index isn't broken
    - { from: "json.BlockNum", to: "json.blockNum", type: "integer" }
    - { from: "json.MsgBlockNum", type: "integer" }
    - { from: "json.myEpoch", type: "integer" }
    - { from: "json.myBlock", type: "integer" }
    - { from: "json.myViewID", type: "integer" }
    - { from: "json.myShardID", type: "integer" }
    ignore_missing: true
    fail_on_error: false
```

**Comment by nyetwurk** [comment]
Also somewhat related to #1334

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Pull request merged**
