### PR TITLE
Add wallet addess to BINGO messages

### PR DESCRIPTION
**Pull request by charleszqwang**
-resolves issue #1321

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by charleszqwang** [comment]
ok to test

**Comment by LeoHChen** [comment]
Failed travis on goimport.

**Comment by LeoHChen** [comment]
please submit the change to r3 branch.  And provide a short test log in the comment.

**Pull request closed without merging**
