### PR TITLE
Log common.Hash in hex instead of TerminalString/Bytes

### PR DESCRIPTION
**Pull request by hsienchiaolee**
## Issue

#1171 

Before:
• Bytes: `\x02�\x1c\vT�g\x1a\x03uQ���u\vZ&7��\x02\x17��8�%���h`
• TerminalString: `c046f9…943e38`

After:
• Hex: `0x6a732f9f1e773540d67253ef618bea0f12c0c293dcb4cb663f186ef4b58a3f01`

## Test
N/A, ran `./test/test_before_submit.sh`.

## TODO
~Blocked on other relating PRs to be merged. For now, please only review commit: cd6e66
Will rebase branch after:~
• #1192 
• #1193 

Update: Rebased `master`

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by mikedoan** [comment]
Jenkins, test this please.

**Comment by mikedoan** [comment]
Jenkins, test this please.

**Comment by mikedoan** [comment]
Jenkins, test this please.

**Comment by hsienchiaolee** [comment]
Rebased master

**Pull request merged**
