### PR TITLE
[logging] add verbosity flag to bootnode, txgen, harmony cmd

### LINKED ISSUE #440: log level support
## Summary

Our current logging doesn't support dynamic log control. We want a finer degree of control for log level.

## Current Design

We have a log package in utils. And we usually use log.GetLogInstance() function to print out log message.
The function we used has level support like Info(), Debug(), Error(), etc. However, we are outputting all the logs right now and there is no way to control the output.

## Problems

We have log level like info/debug/warn, but we can't control the output of log level dynamically.  For example, in a regular run, I don't want to see all the debug log.  But for my testing and debug, I want to see all the debug log. 

## Proposal

1. Use a command line option to support dynamic log level, for example, like -debug to output all debug logs.
2. Provide a dynamic mechanism to control the log level in runtime, for example, send a special command to the node program to control the level of output log.  So that we can enable the log during debugging and no need to re-start the program.

### PR DESCRIPTION
**Pull request by touhonoob**
## Issue

to resolve #440 

## TODO

- [x] add verbosity flag to bootnode, txgen, harmony cmd
- [x] add an api to change verbosity on runtime, test with `curl -H "Content-Type: application/json" -d '{"method":"hmy_setLogVerbosity","params":[0],"id":1}' http://localhost:9010`

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by rlan35** [comment]
Generally, lgtm. Thanks for the effort. Please let us know when it's completed.

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by LeoHChen** [comment]
# github.com/harmony-one/harmony/internal/hmyapi
internal/hmyapi/backend.go:23:15: undefined: namespace
internal/hmyapi/backend.go:25:15: undefined: NewDebugAPI
golang.org/x/crypto/ssh/terminal

**Comment by touhonoob** [comment]
@LeoHChen @rlan35 ready for review

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by touhonoob** [comment]
rebased on master

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by touhonoob** [comment]
Hi @LeoHChen 
Is there a way for external contributors to see error messages from Harmony's Jenkins? I tried to click the details then it asks me to let it access all of my repositories..
Selection_060

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Comment by LeoHChen** [comment]
The change still have problem.  Can't reach consensus in Jenkins test.

**Comment by LeoHChen** [comment]
@touhonoob , I think I knew the reason is probably the log level.  Can you change the default level to 5?  Our post analysis script is looking for some message to check the consensus.  Unfortunately, those message are debug messages.  If you change the default level to 5, we should see Jenkins pass. Thanks.

**Comment by touhonoob** [comment]
Thanks for the tips @LeoHChen. Updated in https://github.com/harmony-one/harmony/pull/844/commits/d9b8fe57ca0d8681234fd119b2e95b6e78c38ba6

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Pull request merged**
