### PR TITLE
High throughput txgen [WIP]

### PR DESCRIPTION
**Pull request by alajko**
High throughput TXGen

- [ ]  Lot of "nonce too low" issues still.
- [ ] On high tps  txgen stuck at 2 consensus (even for shard 0)
- [ ] [SYNC] downloadBlocks: failed to DecodeBytes from received new block

### CODE REVIEW

**Comment by alajko** [comment]
Jenkins, test this please.

**Comment by alajko** [comment]
Jenkins, test this please

**Comment by alajko** [comment]
Jenkins, test this please

**Comment by alajko** [comment]
Jenkins, test this please

**Comment by alajko** [comment]
Jenkins, test this please

**Comment by alajko** [comment]
Jenkins, test this please

**Comment by LeoHChen** [comment]
please use your own repo.   I'll close this PR by tomorrow. Thanks.

**Comment by alajko** [comment]
The PR is off my own repo. Feel free to close it, I started a different branch.

**Pull request closed without merging**
