### PR TITLE
Log blockEpoch and blockNumber as Uint64 not Str

### PR DESCRIPTION
**Pull request by nyetwurk**
Fix issue #1333

### CODE REVIEW

**Comment by harmony-ek** [comment]
Jenkins speaking; can one of the admins verify this patch?

**Comment by nyetwurk** [comment]
This did not fail due to my change :(
```
--- FAIL: TestWalletNotifications (1.40s)
    keystore_test.go:344: wallet list doesn't match required accounts: have 541, want 540
    keystore_test.go:372: can't find event with Kind=0 for 78f30bb77d74f89378b8e4d66cc4ef4417fb15b6
```

**Comment by nyetwurk** [comment]
jenkins, test this please.

**Comment by nyetwurk** [comment]
retest this please

**Comment by LeoHChen** [comment]
Jenkins, test this please.

**Pull request merged**
